const heroes_talents =
{
	lucio:
	[
		[
			"storm_ui_icon_lucio_crossfade_all",
			"storm_ui_icon_lucio_wallride",
			"storm_ui_icon_lucio_wallride_a"
		],
		[
			"storm_ui_icon_lucio_soundwave",
			"storm_ui_icon_lucio_soundwave_a",
			"storm_ui_icon_lucio_accelerando"
		],
		[
			"storm_ui_icon_lucio_soundwave_a",
			"storm_ui_icon_lucio_crossfade_all",
			"storm_ui_icon_lucio_fineshrine"
		],
		[
			"storm_ui_icon_lucio_soundbarrier",
			"storm_ui_icon_lucio_highfive"
		],
		[
			"storm_ui_icon_lucio_crossfade_all",
			"storm_ui_icon_lucio_accelerando",
			"storm_ui_icon_lucio_wallride"
		],
		[
			"storm_ui_icon_lucio_ampitup",
			"storm_ui_icon_lucio_ampitup_b",
			"storm_ui_icon_lucio_ampitup_a"
		],
		[
			"storm_ui_icon_lucio_soundbarrier",
			"storm_ui_icon_lucio_highfive",
			"storm_ui_icon_lucio_crossfade_all",
			"storm_ui_icon_lucio_crossfade_a"
		]
	],

	hogger:
	[
		[
			"storm_ui_icon_hogger_w",
			"storm_ui_icon_hogger_trait",
			"storm_ui_icon_hogger_rage"
		],
		[
			"storm_ui_icon_hogger_combo_q_d",
			"storm_ui_icon_hogger_e",
			"storm_ui_icon_hogger_rage"
		],
		[
			"storm_ui_icon_hogger_combo_q_e",
			"storm_ui_icon_hogger_w",
			"storm_ui_icon_hogger_trait"
		],
		[
			"storm_ui_icon_hogger_r1",
			"storm_ui_icon_hogger_r2"
		],
		[
			"storm_ui_icon_hogger_e",
			"storm_ui_icon_hogger_e_variant",
			"storm_ui_icon_talent_autoattack_heal"
		],
		[
			"storm_ui_icon_hogger_q",
			"storm_ui_icon_hogger_w",
			"storm_ui_icon_talent_autoattack_damage"
		],
		[
			"storm_ui_icon_hogger_r1",
			"storm_ui_icon_hogger_r2",
			"storm_ui_icon_hogger_e_variant",
			"storm_ui_icon_hogger_rage"
		]
	],

	murky:
	[
		[
			"storm_ui_icon_murky_trait_spawnegg",
			"storm_ui_icon_murky_egghunt",
			"storm_ui_icon_talent_bribe"
		],
		[
			"storm_ui_icon_murky_slime",
			"storm_ui_icon_murky_pufferfish",
			"storm_ui_icon_murky_trait_spawnegg_var1"
		],
		[
			"storm_ui_icon_murky_slime",
			"storm_ui_icon_murky_safetybubble",
			"storm_ui_icon_talent_autoattack_slow"
		],
		[
			"storm_ui_icon_murky_marchofthemurlocs",
			"storm_ui_icon_murky_octograb"
		],
		[
			"storm_ui_icon_murky_safetybubble",
			"storm_ui_icon_murky_trait_spawnegg",
			"storm_ui_icon_murky_fishtank"
		],
		[
			"storm_ui_icon_murky_slime",
			"storm_ui_icon_murky_pufferfish",
			"storm_ui_icon_murky_pufferfish_b"
		],
		[
			"storm_ui_icon_murky_marchofthemurlocs",
			"storm_ui_icon_murky_octograb",
			"storm_ui_ingame_heroselect_btn_murky",
			"storm_ui_icon_murky_slime"
		]
	],

	etc:
	[
		[
			"storm_ui_icon_etc_guitarsolo",
			"storm_ui_icon_etc_guitarsolo_a",
			"storm_ui_icon_etc_rockstar"
		],
		[
			"storm_ui_icon_etc_powerslide",
			"storm_ui_icon_etc_facemelt",
			"storm_ui_icon_etc_speedmetal"
		],
		[
			"storm_ui_icon_etc_facemelt",
			"storm_ui_icon_etc_guitarsolo",
			"storm_ui_icon_etc_echopedal"
		],
		[
			"storm_ui_icon_etc_moshpit",
			"storm_ui_icon_etc_stagedive"
		],
		[
			"storm_ui_icon_etc_facemelt",
			"storm_ui_icon_etc_facemelt_a",
			"storm_ui_icon_etc_facemelt_b"
		],
		[
			"storm_ui_icon_etc_powerslide",
			"storm_ui_icon_etc_guitarsolo",
			"storm_ui_icon_talent_imposingpresence"
		],
		[
			"storm_ui_icon_etc_moshpit",
			"storm_ui_icon_etc_stagedive",
			"storm_ui_icon_etc_moshpit_a",
			"storm_ui_icon_talent_stormshield",
			"storm_ui_icon_talent_boltofthestorm"
		]
	],

	sylvanas:
	[
		[
			"storm_ui_icon_sylvanas_witheringfire",
			"storm_ui_icon_sylvanas_shadowdagger",
			"storm_ui_icon_sylvanas_blackarrows"
		],
		[
			"storm_ui_icon_sylvanas_shadowdagger",
			"storm_ui_icon_sylvanas_blackarrows",
			"storm_ui_icon_sylvanas_possession"
		],
		[
			"storm_ui_icon_sylvanas_witheringfire",
			"storm_ui_icon_sylvanas_shadowdagger",
			"storm_ui_icon_sylvanas_hauntingwave"
		],
		[
			"storm_ui_icon_sylvanas_wailingarrow",
			"storm_ui_icon_sylvanas_mindcontrol"
		],
		[
			"storm_ui_icon_sylvanas_shadowdagger",
			"storm_ui_icon_sylvanas_hauntingwave",
			"storm_ui_icon_talent_autoattack_damage"
		],
		[
			"storm_ui_icon_sylvanas_witheringfire",
			"storm_ui_icon_talent_autoattack_heal",
			"storm_ui_icon_sylvanas_willoftheforsaken"
		],
		[
			"storm_ui_icon_sylvanas_wailingarrow",
			"storm_ui_icon_sylvanas_mindcontrol",
			"storm_ui_icon_sylvanas_witheringfire",
			"storm_ui_icon_talent_boltofthestorm"
		]
	],

	cho:
	[
		[
			"storm_ui_icon_cho_consumingflame",
			"storm_ui_icon_cho_ogrehide",
			"storm_ui_icon_cho_ogrehide_var1"
		],
		[
			"storm_ui_icon_cho_moltensurge_a",
			"storm_ui_icon_cho_runebomb",
			"storm_ui_icon_talent_autoattack_damage"
		],
		[
			"storm_ui_icon_cho_moltensurge_a",
			"storm_ui_icon_cho_consumingflame",
			"storm_ui_icon_cho_ogrehide"
		],
		[
			"storm_ui_icon_cho_hammeroftwilight",
			"storm_ui_icon_cho_upheaval"
		],
		[
			"storm_ui_icon_cho_moltensurge_a",
			"storm_ui_icon_talent_hardenedshield",
			"storm_ui_icon_cho_moltenblock"
		],
		[
			"storm_ui_icon_cho_moltensurge_a",
			"storm_ui_icon_cho_runebomb",
			"storm_ui_icon_talent_autoattack_cooldown"
		],
		[
			"storm_ui_icon_cho_hammeroftwilight",
			"storm_ui_icon_cho_upheaval",
			"storm_ui_icon_talent_autoattack_damage",
			"storm_ui_icon_gall_psychoticbreak"
		]
	],

	maiev:
	[
		[
			"storm_ui_icon_maiev_umbra_1",
			"storm_ui_icon_maiev_pursuit_vengeance",
			"storm_ui_icon_maiev_memento"
		],
		[
			"storm_ui_icon_maiev_knives",
			"storm_ui_icon_maiev_knives_2",
			"storm_ui_icon_maiev_rush_2"
		],
		[
			"storm_ui_icon_maiev_knives",
			"storm_ui_icon_maiev_orb_corruption",
			"storm_ui_icon_maiev_rush_1"
		],
		[
			"storm_ui_icon_maiev_heroic_1_a",
			"storm_ui_icon_maiev_heroic_2"
		],
		[
			"storm_ui_icon_maiev_knives",
			"storm_ui_icon_maiev_umbra_1",
			"storm_ui_icon_maiev_rush_2"
		],
		[
			"storm_ui_icon_maiev_knives",
			"storm_ui_icon_maiev_umbra_1",
			"storm_ui_icon_maiev_heavy_strikes"
		],
		[
			"storm_ui_icon_maiev_shadoworb_vengeance",
			"storm_ui_icon_maiev_shadoworb_relentless",
			"storm_ui_icon_maiev_shadoworb_strike"
		]
	],

	arthas:
	[
		[
			"storm_ui_icon_arthas_howlingblast",
			"storm_ui_icon_arthas_frostmournehungers_off",
			"storm_ui_icon_talent_block"
		],
		[
			"storm_ui_icon_arthas_deathcoil",
			"storm_ui_icon_arthas_frosentempest",
			"storm_ui_icon_arthas_frosentempest_a"
		],
		[
			"storm_ui_icon_arthas_deathcoil",
			"storm_ui_icon_arthas_runetap",
			"storm_ui_icon_talent_icebound_fortitude"
		],
		[
			"storm_ui_icon_arthas_armyofthedead",
			"storm_ui_icon_arthas_summonsindragosa"
		],
		[
			"storm_ui_icon_arthas_howlingblast",
			"storm_ui_icon_arthas_frosentempest",
			"storm_ui_icon_arthas_frostmournehungers_off"
		],
		[
			"storm_ui_icon_arthas_deathcoil",
			"storm_ui_icon_arthas_frosentempest",
			"storm_ui_icon_arthas_frostmournehungers_off"
		],
		[
			"storm_ui_icon_arthas_armyofthedead",
			"storm_ui_icon_arthas_summonsindragosa",
			"storm_ui_icon_arthas_frosentempest",
			"storm_temp_war3_btnantimagicshell"
		]
	],

	valeera:
	[
		[
			"storm_ui_icon_talent_conjurerspursuit",
			"storm_ui_icon_valeera_vanish",
			"storm_ui_icon_talent_block",
			"storm_ui_icon_valeera_cripplingpoison"
		],
		[
			"storm_ui_icon_valeera_sinisterstrike",
			"storm_ui_icon_valeera_garrote",
			"storm_ui_icon_valeera_vanish",
			"storm_ui_icon_valeera_woundpoison"
		],
		[
			"storm_ui_icon_valeera_sinisterstrike",
			"storm_ui_icon_valeera_bladeflurry",
			"storm_ui_icon_valeera_eviscerate"
		],
		[
			"storm_ui_icon_valeera_smokebomb",
			"storm_ui_icon_valeera_cloakofshadows"
		],
		[
			"storm_ui_icon_valeera_ambush",
			"storm_ui_icon_valeera_cheapshot",
			"storm_ui_icon_valeera_garrote"
		],
		[
			"storm_ui_icon_valeera_sinisterstrike",
			"storm_ui_icon_valeera_ambush",
			"storm_ui_icon_valeera_thistletea"
		],
		[
			"storm_ui_icon_valeera_smokebomb",
			"storm_ui_icon_valeera_cloakofshadows",
			"storm_ui_icon_valeera_garrote",
			"storm_ui_icon_valeera_vanish"
		]
	],

	valla:
	[
		[
			"storm_ui_icon_valla_hungeringarrow",
			"storm_ui_icon_valla_multishot",
			"storm_ui_icon_valla_hatred"
		],
		[
			"storm_ui_icon_valla_multishot",
			"storm_ui_icon_valla_vault",
			"storm_ui_icon_valla_repeatingarrow"
		],
		[
			"storm_ui_icon_valla_hungeringarrow",
			"storm_ui_icon_valla_siphoningarrow",
			"storm_ui_icon_valla_hatred"
		],
		[
			"storm_ui_icon_valla_strafe",
			"storm_ui_icon_valla_rainofvengeance"
		],
		[
			"storm_ui_icon_valla_siphoningarrow",
			"storm_ui_icon_valla_hatred",
			"storm_ui_icon_valla_hatred_var1"
		],
		[
			"storm_ui_icon_valla_multishot",
			"storm_ui_icon_valla_hatred",
			"storm_ui_icon_talent_autoattack_damage"
		],
		[
			"storm_ui_icon_valla_strafe",
			"storm_ui_icon_valla_rainofvengeance",
			"storm_ui_icon_valla_vault",
			"storm_ui_icon_valla_hatred"
		]
	],

	sgthammer:
	[
		[
			"storm_ui_icon_sgthammer_siegemode_var2",
			"storm_ui_icon_sgthammer_siegemode",
			"storm_ui_icon_sgthammer_siegemode_var1"
		],
		[
			"storm_ui_icon_sgthammer_concussiveblast",
			"storm_ui_icon_sgthammer_neosteelplating",
			"storm_ui_icon_sgthammer_siegemode"
		],
		[
			"storm_ui_icon_sgthammer_spidermines",
			"storm_ui_icon_sgthammer_siegemode",
			"storm_ui_icon_sgthammer_siegemode_var1"
		],
		[
			"storm_ui_icon_sgthammer_bluntforcegun",
			"storm_ui_icon_sgthammer_napalmstrike"
		],
		[
			"storm_ui_icon_sgthammer_spidermines",
			"storm_ui_icon_sgthammer_concussiveblast",
			"storm_ui_icon_sgthammer_hypercoolingengines"
		],
		[
			"storm_ui_icon_sgthammer_neosteelplating",
			"storm_ui_icon_talent_autoattack_damage",
			"storm_ui_icon_talent_autoattack_searing"
		],
		[
			"storm_ui_icon_sgthammer_bluntforcegun",
			"storm_ui_icon_sgthammer_napalmstrike",
			"storm_ui_icon_sgthammer_spidermines",
			"storm_ui_icon_sgthammer_siegemode"
		]
	],

	leoric:
	[
		[
			"storm_ui_icon_leoric_skeletalswing",
			"storm_ui_icon_leoric_trait",
			"storm_ui_icon_talent_amplifiedhealing"
		],
		[
			"storm_ui_icon_leoric_skeletalswing",
			"storm_ui_icon_leoric_skeletalswing_var1",
			"storm_ui_icon_leoric_skeletalswing_var2"
		],
		[
			"storm_ui_icon_leoric_drainhope",
			"storm_ui_icon_leoric_drainhope_var1",
			"storm_ui_icon_leoric_drainhope_var2"
		],
		[
			"storm_ui_icon_leoric_entomb",
			"storm_ui_icon_leoric_r2"
		],
		[
			"storm_ui_icon_leoric_drainhope",
			"storm_ui_icon_leoric_wraithwalk",
			"storm_ui_icon_talent_autoattack_heal"
		],
		[
			"storm_ui_icon_leoric_drainhope",
			"storm_ui_icon_leoric_wraithwalk",
			"storm_ui_icon_talent_autoattack_speed"
		],
		[
			"storm_ui_icon_leoric_entomb",
			"storm_ui_icon_leoric_r2",
			"storm_ui_icon_leoric_drainhope",
			"storm_ui_icon_talent_hardenedshield"
		]
	],

	probius:
	[
		[
			"storm_ui_icon_probius_disruptionpulse",
			"storm_ui_icon_probius_warprift",
			"storm_ui_icon_probius_photoncannon"
		],
		[
			"storm_ui_icon_probius_photoncannon",
			"storm_ui_icon_probius_workerrush",
			"storm_ui_icon_probius_shieldcapacitor"
		],
		[
			"storm_ui_icon_probius_disruptionpulse",
			"storm_ui_icon_probius_warprift",
			"storm_ui_icon_probius_photoncannon"
		],
		[
			"storm_ui_icon_probius_pylonovercharge",
			"storm_ui_icon_probius_voidgate"
		],
		[
			"storm_ui_icon_probius_warpinpylon",
			"storm_ui_icon_probius_warpinpylon_a",
			"storm_ui_icon_probius_warpinpylon_b"
		],
		[
			"storm_ui_icon_probius_warprift",
			"storm_ui_icon_probius_warprift_a",
			"storm_ui_icon_probius_warprift_c"
		],
		[
			"storm_ui_icon_probius_pylonovercharge",
			"storm_ui_icon_probius_voidgate",
			"storm_ui_icon_probius_disruptionpulse",
			"storm_ui_icon_probius_warprift"
		]
	],

	johanna:
	[
		[
			"storm_ui_icon_johanna_shield_glare",
			"storm_ui_icon_talent_block",
			"storm_ui_icon_johanna_lawsofhope"
		],
		[
			"storm_ui_icon_johanna_punish",
			"storm_ui_icon_johanna_condemn",
			"storm_ui_icon_johanna_iron_skin"
		],
		[
			"storm_ui_icon_johanna_punish",
			"storm_ui_icon_johanna_condemn",
			"storm_btn_d3ros_crusader_steedcharge"
		],
		[
			"storm_ui_icon_johanna_falling_sword",
			"storm_ui_icon_johanna_blessed_shield"
		],
		[
			"storm_ui_icon_johanna_punish",
			"storm_ui_icon_talent_burningrage",
			"storm_btn_d3ros_crusader_blessedhammer"
		],
		[
			"storm_ui_icon_johanna_condemn",
			"storm_ui_icon_johanna_shield_glare",
			"storm_ui_icon_talent_autoattack_cooldown"
		],
		[
			"storm_ui_icon_johanna_falling_sword",
			"storm_ui_icon_johanna_blessed_shield",
			"storm_ui_icon_johanna_indestructible",
			"storm_ui_icon_talent_stormshield"
		]
	],

	malthael:
	[
		[
			"storm_ui_icon_malthael_wraithstrike",
			"storm_ui_icon_malthael_onpalehorse",
			"storm_ui_icon_malthael_fearthereaper"
		],
		[
			"storm_ui_icon_malthael_soulrip",
			"storm_ui_icon_malthael_deathshroud",
			"storm_ui_icon_malthael_reapersmark"
		],
		[
			"storm_ui_icon_malthael_soulrip",
			"storm_ui_icon_malthael_wraithstrike",
			"storm_ui_icon_malthael_touchofdeath"
		],
		[
			"storm_ui_icon_malthael_tormentedsoul",
			"storm_ui_icon_malthael_lastrites"
		],
		[
			"storm_ui_icon_malthael_soulrip",
			"storm_ui_icon_malthael_reapersmark",
			"storm_ui_icon_malthael_inevitableend",
			"storm_ui_icon_malthael_shroudofwisdom"
		],
		[
			"storm_ui_icon_malthael_soulrip",
			"storm_ui_icon_malthael_wraithstrike",
			"storm_ui_icon_malthael_reapersmark"
		],
		[
			"storm_ui_icon_malthael_tormentedsoul",
			"storm_ui_icon_malthael_lastrites",
			"storm_ui_icon_malthael_deathshroud",
			"storm_ui_icon_malthael_noonecanstopdeath"
		]
	],

	stukov:
	[
		[
			"storm_ui_icon_stukov_weightedpustule",
			"storm_ui_icon_stukov_weightedpustule_a",
			"storm_ui_icon_stukov_lurkingarm"
		],
		[
			"storm_ui_icon_stukov_healingpathogen",
			"storm_ui_icon_stukov_healingpathogen_b",
			"storm_ui_icon_stukov_biokillswitch"
		],
		[
			"storm_ui_icon_stukov_weightedpustule",
			"storm_ui_icon_stukov_lurkingarm",
			"storm_ui_icon_stukov_biokillswitch"
		],
		[
			"storm_ui_icon_stukov_flailingswipe",
			"storm_ui_icon_stukov_massiveshove"
		],
		[
			"storm_ui_icon_stukov_lurkingarm",
			"storm_ui_icon_stukov_lurkingarm_a",
			"storm_ui_icon_stukov_biokillswitch"
		],
		[
			"storm_ui_icon_stukov_healingpathogen",
			"storm_ui_icon_stukov_healingpathogen_a",
			"storm_ui_icon_stukov_biokillswitch"
		],
		[
			"storm_ui_icon_stukov_flailingswipe",
			"storm_ui_icon_stukov_massiveshove",
			"storm_ui_icon_stukov_healingpathogen",
			"storm_ui_icon_stukov_biokillswitch"
		]
	],

	ana:
	[
		[
			"storm_ui_icon_ana_biotic_grenade",
			"storm_ui_icon_ana_sleep_dart",
			"storm_ui_icon_ana_shrike"
		],
		[
			"storm_ui_icon_ana_biotic_grenade",
			"storm_ui_icon_ana_sleep_dart",
			"storm_ui_icon_ana_debilitatingdart"
		],
		[
			"storm_ui_icon_ana_biotic_grenade",
			"storm_ui_icon_ana_sleep_dart",
			"storm_ui_icon_ana_shrike"
		],
		[
			"storm_ui_icon_ana_nano_bost",
			"storm_ui_icon_ana_overwatch"
		],
		[
			"storm_ui_icon_ana_healing_dart",
			"storm_ui_icon_ana_healing_dart_a",
			"storm_ui_icon_ana_healing_dart_b"
		],
		[
			"storm_ui_icon_ana_healing_dart",
			"storm_ui_icon_ana_healing_dart_a",
			"storm_ui_icon_ana_healing_dart_b"
		],
		[
			"storm_ui_icon_ana_nano_bost",
			"storm_ui_icon_ana_overwatch",
			"storm_ui_icon_ana_aim_down_sights",
			"storm_ui_icon_ana_aim_down_sights_a"
		]
	],

	orphea:
	[
		[
			"storm_ui_icon_orphea_q",
			"storm_ui_icon_orphea_e",
			"storm_ui_icon_orphea_trait"
		],
		[
			"storm_ui_icon_orphea_q",
			"storm_ui_icon_orphea_w",
			"storm_ui_icon_orphea_trait"
		],
		[
			"storm_ui_icon_orphea_w",
			"storm_ui_icon_orphea_w_2",
			"storm_ui_icon_orphea_e"
		],
		[
			"storm_ui_icon_orphea_ult_darkfall",
			"storm_ui_icon_orphea_ult_thrasher"
		],
		[
			"storm_ui_icon_orphea_q",
			"storm_ui_icon_orphea_w",
			"storm_ui_icon_orphea_trait"
		],
		[
			"storm_ui_icon_orphea_q",
			"storm_ui_icon_orphea_trait",
			"storm_ui_icon_orphea_e_terror"
		],
		[
			"storm_ui_icon_orphea_ult_darkfall",
			"storm_ui_icon_orphea_ult_thrasher",
			"storm_ui_icon_orphea_trait",
			"storm_ui_icon_orphea_reset"
		]
	],

	thrall:
	[
		[
			"storm_ui_icon_thrall_chainlightning",
			"storm_ui_icon_thrall_chainlightning_var1",
			"storm_ui_icon_thrall_chainlightning_var2"
		],
		[
			"storm_ui_icon_thrall_feralspirit",
			"storm_ui_icon_thrall_feralspirit_var1",
			"storm_ui_icon_thrall_frostwolfresilience"
		],
		[
			"storm_ui_icon_thrall_windfury_var1",
			"storm_ui_icon_talent_bloodforblood",
			"storm_ui_icon_talent_autoattack_damage"
		],
		[
			"storm_ui_icon_thrall_sundering",
			"storm_ui_icon_thrall_earthquake"
		],
		[
			"storm_ui_icon_thrall_windfury",
			"storm_ui_icon_thrall_frostwolfresilience",
			"storm_ui_icon_talent_spellshield"
		],
		[
			"storm_ui_icon_thrall_windfury",
			"storm_ui_icon_thrall_chainlightning",
			"storm_ui_icon_thrall_feralspirit"
		],
		[
			"storm_ui_icon_thrall_sundering",
			"storm_ui_icon_thrall_earthquake",
			"storm_ui_icon_talent_autoattack_cooldown",
			"storm_ui_icon_talent_autoattack_slow",
			"storm_ui_icon_talent_boltofthestorm"
		]
	],

	zeratul:
	[
		[
			"storm_ui_icon_zeratul_cleave",
			"storm_ui_icon_zeratul_blink",
			"storm_ui_icon_zeratul_cloak"
		],
		[
			"storm_ui_icon_zeratul_cleave",
			"storm_ui_icon_talent_abilitytalent_damage",
			"storm_ui_icon_zeratul_shadowassault"
		],
		[
			"storm_ui_icon_zeratul_blink",
			"storm_ui_icon_zeratul_singularityspike",
			"storm_ui_icon_zeratul_vorpalblade"
		],
		[
			"storm_ui_icon_zeratul_mightofnerazim",
			"storm_ui_icon_zeratul_voidprison"
		],
		[
			"storm_ui_icon_zeratul_cloak",
			"storm_ui_icon_talent_autoattack_heal",
			"storm_ui_icon_talent_spellshield"
		],
		[
			"storm_ui_icon_talent_autoattack_damage",
			"storm_ui_icon_zeratul_cleave",
			"storm_ui_icon_zeratul_singularityspike"
		],
		[
			"storm_ui_icon_zeratul_mightofnerazim",
			"storm_ui_icon_zeratul_singularityspike",
			"storm_ui_icon_zeratul_vorpalblade",
			"storm_ui_icon_talent_abilitytalent_heal"
		]
	],

	azmodan:
	[
		[
			"storm_ui_icon_azmodan_globeofannihilation",
			"storm_ui_icon_azmodan_globeofannihilation_a",
			"storm_ui_icon_azmodan_globeofannihilation_b"
		],
		[
			"storm_ui_icon_azmodan_summondemonwarrior",
			"storm_ui_icon_azmodan_summondemonwarrior_a",
			"storm_ui_icon_talent_autoattack_cooldown"
		],
		[
			"storm_ui_icon_azmodan_globeofannihilation",
			"storm_ui_icon_azmodan_globeofannihilation_a",
			"storm_ui_icon_azmodan_allshallburn"
		],
		[
			"storm_ui_icon_azmodan_demonicinvasion",
			"storm_ui_icon_azmodan_blackpool"
		],
		[
			"storm_ui_icon_azmodan_summondemonwarrior",
			"storm_ui_icon_azmodan_allshallburn",
			"storm_ui_icon_azmodan_generalofhell"
		],
		[
			"storm_ui_icon_azmodan_globeofannihilation",
			"storm_ui_icon_azmodan_allshallburn",
			"storm_ui_icon_azmodan_trample"
		],
		[
			"storm_ui_icon_azmodan_demonicinvasion",
			"storm_ui_icon_azmodan_blackpool",
			"storm_ui_icon_azmodan_globeofannihilation",
			"storm_ui_icon_azmodan_allshallburn"
		]
	],

	deathwing:
	[
		[
			"storm_ui_icon_deathwing_heat_wave",
			"storm_ui_icon_deathwing_aspect_of_death",
			"storm_ui_icon_deathwing_aspect_of_death_alt1"
		],
		[
			"storm_ui_icon_deathwing_molten_flame",
			"storm_ui_icon_deathwing_heat_wave",
			"storm_ui_icon_deathwing_aspect_of_death"
		],
		[
			"storm_ui_icon_deathwing_firestorm",
			"storm_ui_icon_deathwing_deathdrop",
			"storm_ui_icon_deathwing_skyfall"
		],
		[
			"storm_ui_icon_deathwing_cataclysm",
			"storm_ui_icon_deathwing_bellowing_roar"
		],
		[
			"storm_ui_icon_deathwing_molten_flame",
			"storm_ui_icon_deathwing_ruination",
			"storm_ui_icon_deathwing_fire_and_fury"
		],
		[
			"storm_ui_icon_deathwing_molten_flame",
			"storm_ui_icon_deathwing_deathdrop",
			"storm_ui_icon_deathwing_elemental_plating"
		],
		[
			"storm_ui_icon_deathwing_cataclysm",
			"storm_ui_icon_deathwing_deathdrop",
			"storm_ui_icon_deathwing_destroyer"
		]
	],

	lunara:
	[
		[
			"storm_ui_icon_lunara_wisp",
			"storm_ui_icon_lunara_stiflingblossom",
			"storm_ui_icon_lunara_boundlessstride_a"
		],
		[
			"storm_ui_icon_lunara_pollencloud",
			"storm_ui_icon_lunara_stiflingblossom_var1",
			"storm_ui_icon_lunara_stiflingblossom"
		],
		[
			"storm_ui_icon_lunara_pollencloud",
			"storm_ui_icon_lunara_pollencloud_b",
			"storm_ui_icon_lunara_fullbloom"
		],
		[
			"storm_ui_icon_lunara_wildspear",
			"storm_ui_icon_lunara_boundlessstride"
		],
		[
			"storm_ui_icon_lunara_fullbloom",
			"storm_ui_icon_lunara_fullbloom_b",
			"storm_ui_icon_lunara_greaterspellshield",
			"storm_ui_icon_lunara_abolishmagic"
		],
		[
			"storm_ui_icon_lunara_pollencloud",
			"storm_ui_icon_lunara_fullbloom",
			"storm_ui_icon_lunara_fullbloom_a",
			"storm_ui_icon_lunara_stiflingblossom"
		],
		[
			"storm_ui_icon_lunara_wildspear",
			"storm_ui_icon_lunara_boundlessstride",
			"storm_ui_icon_lunara_stiflingblossom",
			"storm_ui_icon_lunara_boundlessstride_a"
		]
	],

	alarak:
	[
		[
			"storm_ui_icon_alarak_discordstrike",
			"storm_ui_icon_alarak_telekinesis",
			"storm_ui_icon_alarak_lightningsurge"
		],
		[
			"storm_ui_icon_alarak_discordstrike",
			"storm_ui_icon_alarak_lightningsurge",
			"storm_ui_icon_alarak_sadism"
		],
		[
			"storm_ui_icon_alarak_discordstrike",
			"storm_ui_icon_alarak_telekinesis_a",
			"storm_ui_icon_alarak_telekinesis"
		],
		[
			"storm_ui_icon_alarak_recklesscharge",
			"storm_ui_icon_alarak_counterstrike"
		],
		[
			"storm_ui_icon_alarak_sadism",
			"storm_ui_icon_alarak_sadism_a",
			"storm_ui_icon_alarak_sadism_b"
		],
		[
			"storm_ui_icon_alarak_discordstrike",
			"storm_ui_icon_alarak_lightningsurge",
			"storm_ui_icon_talent_autoattack_cooldown"
		],
		[
			"storm_ui_icon_alarak_counterstrike",
			"storm_ui_icon_alarak_recklesscharge",
			"storm_ui_icon_alarak_lasttrick",
			"storm_ui_icon_alarak_hastybargain"
		]
	],

	nova:
	[
		[
			"storm_ui_icon_nova_pinningshot",
			"storm_ui_icon_nova_pinningshot_var1",
			"storm_ui_icon_nova_personalcloaking"
		],
		[
			"storm_ui_icon_nova_holodecoy_var1",
			"storm_ui_icon_nova_holodecoy_var2",
			"storm_ui_icon_talent_bribe"
		],
		[
			"storm_ui_icon_nova_snipe",
			"storm_ui_icon_talent_autoattack_damage",
			"storm_ui_icon_talent_antiarmorshells"
		],
		[
			"storm_ui_icon_nova_tripletap",
			"storm_ui_icon_nova_orbitalstrike"
		],
		[
			"storm_ui_icon_nova_snipe",
			"storm_ui_icon_nova_pinningshot",
			"storm_ui_icon_nova_personalcloaking"
		],
		[
			"storm_ui_icon_nova_snipe",
			"storm_ui_icon_nova_pinningshot",
			"storm_ui_icon_nova_holodecoy"
		],
		[
			"storm_ui_icon_nova_tripletap",
			"storm_ui_icon_nova_orbitalstrike",
			"storm_ui_icon_nova_personalcloaking",
			"storm_ui_icon_talent_rewind"
		]
	],

	zagara:
	[
		[
			"storm_ui_icon_zagara_banelingbarrage",
			"storm_ui_icon_zagara_infesteddrop",
			"storm_ui_icon_zagara_infest"
		],
		[
			"storm_ui_icon_talent_autoattack_range",
			"storm_ui_icon_talent_autoattack_aoe",
			"storm_ui_icon_talent_autoattack_damage"
		],
		[
			"storm_ui_icon_zagara_banelingbarrage",
			"storm_ui_icon_zagara_banelingbarrage_a",
			"storm_ui_icon_zagara_infesteddrop"
		],
		[
			"storm_ui_icon_zagara_devouringmaw",
			"storm_ui_icon_zagara_nydusworm"
		],
		[
			"storm_ui_icon_zagara_hunterkiller",
			"storm_ui_icon_zagara_creep",
			"storm_ui_icon_talent_spellshield"
		],
		[
			"storm_ui_icon_zagara_hunterkiller",
			"storm_ui_icon_zagara_hunterkillermuta",
			"storm_ui_icon_zagara_creep"
		],
		[
			"storm_ui_icon_zagara_devouringmaw",
			"storm_ui_icon_zagara_nydusworm",
			"storm_ui_icon_zagara_banelingbarrage",
			"storm_ui_icon_zagara_hunterkiller"
		]
	],

	rehgar:
	[
		[
			"storm_ui_icon_rehgar_lightningshield",
			"storm_ui_icon_rehgar_earthbindtotem",
			"storm_ui_icon_rehgar_ghostwolf"
		],
		[
			"storm_ui_icon_rehgar_chainheal",
			"storm_ui_icon_rehgar_lightningshield",
			"storm_ui_icon_talent_healingward"
		],
		[
			"storm_ui_icon_rehgar_earthbindtotem",
			"storm_ui_icon_rehgar_purge",
			"storm_ui_icon_rehgar_ghostwolf"
		],
		[
			"storm_ui_icon_rehgar_ancestralhealing",
			"storm_ui_icon_rehgar_bloodlust"
		],
		[
			"storm_ui_icon_rehgar_chainheal",
			"storm_ui_icon_rehgar_lightningshield",
			"storm_ui_icon_rehgar_earthbindtotem"
		],
		[
			"storm_ui_icon_rehgar_lightningshield",
			"storm_ui_icon_rehgar_earthbindtotem",
			"storm_ui_icon_rehgar_ghostwolf"
		],
		[
			"storm_ui_icon_rehgar_ancestralhealing",
			"storm_ui_icon_rehgar_bloodlust",
			"storm_ui_icon_talent_stormshield",
			"storm_ui_ingame_heroselect_btn_rehgar"
		]
	],

	genji:
	[
		[
			"storm_ui_icon_genji_swiftstrike",
			"storm_ui_icon_genji_cyberagility",
			"storm_ui_icon_genji_cyberagility_a"
		],
		[
			"storm_ui_icon_genji_shurikens",
			"storm_ui_icon_genji_swiftstrike",
			"storm_ui_icon_genji_shurikens_dragonsoul"
		],
		[
			"storm_ui_icon_genji_deflect",
			"storm_ui_icon_genji_deflect_a",
			"storm_ui_icon_genji_cyberagility"
		],
		[
			"storm_ui_icon_genji_dragonblade",
			"storm_ui_icon_genji_shurikens_xblade"
		],
		[
			"storm_ui_icon_genji_shurikens",
			"storm_ui_icon_genji_swiftstrike",
			"storm_ui_icon_talent_autoattack_damage"
		],
		[
			"storm_ui_icon_genji_deflect",
			"storm_ui_icon_genji_swiftstrike",
			"storm_ui_icon_genji_swiftstrike_a"
		],
		[
			"storm_ui_icon_genji_dragonblade",
			"storm_ui_icon_genji_shurikens_xblade",
			"storm_ui_icon_genji_shurikens",
			"storm_ui_icon_genji_deflect_b"
		]
	],

	tassadar:
	[
		[
			"storm_ui_icon_tassadar_rework_q_ray",
			"storm_ui_icon_tassadar_psionicstorm",
			"storm_ui_icon_tassadar_rework_trait"
		],
		[
			"storm_ui_icon_tassadar_rework_q_ray",
			"storm_ui_icon_tassadar_forcewall",
			"storm_ui_icon_tassadar_rework_trait"
		],
		[
			"storm_ui_icon_tassadar_rework_q_ray",
			"storm_ui_icon_tassadar_psionicstorm",
			"storm_ui_icon_tassadar_rework_trait"
		],
		[
			"storm_ui_icon_tassadar_archon",
			"storm_ui_icon_tassadar_rework_blackhole"
		],
		[
			"storm_ui_icon_tassadar_psionicstorm",
			"storm_ui_icon_tassadar_dimensionalshift",
			"storm_ui_icon_tassadar_oracle"
		],
		[
			"storm_ui_icon_tassadar_rework_q_ray",
			"storm_ui_icon_tassadar_psionicstorm",
			"storm_temp_btnupgradeprotosskhaydarinamulet"
		],
		[
			"storm_ui_icon_tassadar_archon",
			"storm_ui_icon_tassadar_rework_blackhole",
			"storm_ui_icon_tassadar_forcewall",
			"storm_ui_icon_tassadar_rework_active_khala"
		]
	],

	artanis:
	[
		[
			"storm_ui_icon_artanis_doubleslash_on",
			"storm_ui_icon_artanis_doubleslash_var1",
			"storm_ui_icon_talent_autoattack_damage"
		],
		[
			"storm_ui_icon_artanis_repositionmatrix",
			"storm_ui_icon_artanis_shieldoverload",
			"storm_ui_icon_artanis_shieldoverload_a"
		],
		[
			"storm_ui_icon_artanis_powerstrikes",
			"storm_ui_icon_artanis_repositionmatrix",
			"storm_ui_icon_talent_autoattack_damage"
		],
		[
			"storm_ui_icon_artanis_disruptionweb",
			"storm_ui_icon_artanis_purifierbeam"
		],
		[
			"storm_ui_icon_artanis_powerstrikes",
			"storm_ui_icon_artanis_doubleslash_on",
			"storm_ui_icon_artanis_repositionmatrix",
			"storm_ui_icon_artanis_shieldoverload"
		],
		[
			"storm_ui_icon_artanis_doubleslash_on",
			"storm_ui_icon_artanis_shieldoverload",
			"storm_ui_icon_talent_autoattack_slow"
		],
		[
			"storm_ui_icon_artanis_disruptionweb",
			"storm_ui_icon_artanis_purifierbeam",
			"storm_ui_icon_artanis_doubleslash_on",
			"storm_ui_icon_artanis_shieldoverload"
		]
	],

	liming:
	[
		[
			"storm_ui_icon_wizard_magicmissiles",
			"storm_ui_icon_wizard_teleport",
			"storm_ui_icon_talent_powerhungry"
		],
		[
			"storm_ui_icon_wizard_magicmissiles",
			"storm_ui_icon_wizard_arcaneorb",
			"storm_ui_icon_wizard_criticalmass"
		],
		[
			"storm_ui_icon_wizard_magicmissiles",
			"storm_ui_icon_wizard_arcaneorb",
			"storm_ui_icon_wizard_teleport"
		],
		[
			"storm_ui_icon_wizard_disintegrate",
			"storm_ui_icon_wizard_waveofforce"
		],
		[
			"storm_ui_icon_wizard_teleport",
			"storm_ui_icon_talent_autoattack_damage",
			"storm_btn_d3_traits_wizard_glasscannon"
		],
		[
			"storm_ui_icon_wizard_magicmissiles",
			"storm_ui_icon_wizard_magicmissiles_b",
			"storm_ui_icon_wizard_arcaneorb",
			"storm_ui_icon_wizard_teleport"
		],
		[
			"storm_ui_icon_wizard_disintegrate",
			"storm_ui_icon_wizard_waveofforce",
			"storm_btn_d3_traits_wizard_elementalexposure",
			"storm_ui_icon_wizard_archon"
		]
	],

	falstad:
	[
		[
			"storm_ui_icon_falstad_hammerang",
			"storm_ui_icon_falstad_lightningrod",
			"storm_ui_icon_falstad_tailwind_a"
		],
		[
			"storm_ui_icon_falstad_lightningrod",
			"storm_ui_icon_falstad_barrelroll",
			"storm_ui_icon_talent_autoattack_heal"
		],
		[
			"storm_ui_icon_falstad_hammerang",
			"storm_ui_icon_falstad_hammerang_a",
			"storm_ui_icon_falstad_lightningrod"
		],
		[
			"storm_ui_icon_falstad_hinterlandblast",
			"storm_ui_icon_falstad_mightygust"
		],
		[
			"storm_ui_icon_falstad_lightningrod",
			"storm_ui_icon_falstad_tailwind",
			"storm_ui_icon_falstad_tailwind_a"
		],
		[
			"storm_ui_icon_falstad_hammerang",
			"storm_ui_icon_falstad_tailwind",
			"storm_ui_icon_falstad_barrelroll"
		],
		[
			"storm_ui_icon_falstad_hinterlandblast",
			"storm_ui_icon_falstad_mightygust",
			"storm_ui_icon_talent_autoattack_range",
			"storm_ui_icon_falstad_epicmount"
		]
	],

	jaina:
	[
		[
			"storm_ui_icon_jaina_frostbolt",
			"storm_ui_icon_jaina_frostbite",
			"storm_ui_icon_talent_conjurerspursuit"
		],
		[
			"storm_ui_icon_jaina_frostbolt",
			"storm_ui_icon_jaina_arcaneintellect",
			"storm_ui_icon_jaina_frostarmor"
		],
		[
			"storm_ui_icon_jaina_frostbolt",
			"storm_ui_icon_jaina_coneofcold",
			"storm_ui_icon_talent_autoattack_damage"
		],
		[
			"storm_ui_icon_jaina_ringoffrost",
			"storm_ui_icon_jaina_summonwaterelemental"
		],
		[
			"storm_ui_icon_jaina_blizzard",
			"storm_ui_icon_jaina_frostbite",
			"storm_ui_icon_jaina_icyveins"
		],
		[
			"storm_ui_icon_jaina_blizzard",
			"storm_ui_icon_jaina_coneofcold",
			"storm_ui_icon_jaina_coneofcold_var1"
		],
		[
			"storm_ui_icon_jaina_ringoffrost",
			"storm_ui_icon_jaina_summonwaterelemental",
			"storm_ui_icon_talent_boltofthestorm",
			"storm_ui_icon_jaina_frostbite"
		]
	],

	varian:
	[
		[
			"storm_ui_icon_varian_lionsfang",
			"storm_ui_icon_varian_parry",
			"storm_ui_icon_varian_highkingsquest"
		],
		[
			"storm_ui_icon_varian_taunt",
			"storm_ui_icon_varian_colossus_smash",
			"storm_ui_icon_varian_twinbladesoffury"
		],
		[
			"storm_ui_icon_varian_lionsfang",
			"storm_ui_icon_varian_secondwind",
			"storm_ui_icon_varian_victoryrush"
		],
		[
			"storm_ui_icon_varian_parry",
			"storm_ui_icon_varian_charge"
		],
		[
			"storm_ui_icon_varian_charge",
			"storm_ui_icon_varian_mortalstrike",
			"storm_ui_icon_varian_shatteringthrow"
		],
		[
			"storm_ui_icon_varian_bannerofstormwind",
			"storm_ui_icon_varian_bannerofironforge",
			"storm_ui_icon_varian_bannerofdalaran"
		],
		[
			"storm_ui_icon_varian_taunt",
			"storm_ui_icon_varian_colossus_smash",
			"storm_ui_icon_varian_twinbladesoffury",
			"storm_ui_icon_varian_glorytothealliance",
			"storm_ui_icon_varian_demoralizingshout"
		]
	],

	illidan:
	[
		[
			"storm_ui_icon_illidan_sweepingstrike",
			"storm_ui_icon_illidan_sweepingstrike_a",
			"storm_ui_icon_talent_seasonedmarksman"
		],
		[
			"storm_ui_icon_illidan_dive",
			"storm_ui_icon_illidan_betrayersthirst",
			"storm_ui_icon_illidan_betrayersthirst_a"
		],
		[
			"storm_ui_icon_illidan_dive",
			"storm_ui_icon_illidan_dive_a",
			"storm_ui_icon_illidan_sweepingstrike"
		],
		[
			"storm_ui_icon_illidan_metamorphosis",
			"storm_ui_icon_illidan_thehunt"
		],
		[
			"storm_ui_icon_illidan_sweepingstrike",
			"storm_ui_icon_illidan_evasion",
			"storm_ui_icon_illidan_evasion_a"
		],
		[
			"storm_ui_icon_illidan_dive",
			"storm_ui_icon_talent_autoattack_damage",
			"storm_ui_icon_illidan_sweepingstrike_c"
		],
		[
			"storm_ui_icon_illidan_metamorphosis",
			"storm_ui_icon_illidan_thehunt",
			"storm_ui_icon_talent_autoattack_slow",
			"storm_ui_icon_talent_boltofthestorm"
		]
	],

	nazeebo:
	[
		[
			"storm_ui_icon_nazeebo_corpsespider",
			"storm_ui_icon_nazeebo_plagueoftoads",
			"storm_ui_icon_talent_elunesgrace"
		],
		[
			"storm_ui_icon_nazeebo_corpsespider",
			"storm_ui_icon_nazeebo_voodooritual",
			"storm_ui_icon_nazeebo_voodooritual_a"
		],
		[
			"storm_ui_icon_nazeebo_corpsespider",
			"storm_ui_icon_nazeebo_zombiewall",
			"storm_ui_icon_nazeebo_plagueoftoads"
		],
		[
			"storm_ui_icon_nazeebo_gargantuan",
			"storm_ui_icon_nazeebo_ravenousspirit"
		],
		[
			"storm_ui_icon_nazeebo_plagueoftoads",
			"storm_ui_icon_nazeebo_suprerstition",
			"storm_ui_icon_talent_iceblock"
		],
		[
			"storm_ui_icon_nazeebo_corpsespider",
			"storm_ui_icon_nazeebo_zombiewall",
			"storm_ui_icon_nazeebo_soulharvest"
		],
		[
			"storm_ui_icon_nazeebo_gargantuan",
			"storm_ui_icon_nazeebo_ravenousspirit",
			"storm_ui_icon_nazeebo_voodooritual",
			"storm_ui_icon_nazeebo_voodooritual_a"
		]
	],

	zarya:
	[
		[
			"storm_ui_icon_zarya_particlegrenade",
			"storm_ui_icon_zarya_shieldally",
			"storm_ui_icon_talent_autoattack_base",
			"storm_ui_icon_zarya_energy"
		],
		[
			"storm_ui_icon_zarya_personalbarrier",
			"storm_ui_icon_zarya_shieldally",
			"storm_ui_icon_zarya_shieldally_a",
			"storm_ui_icon_zarya_pumped"
		],
		[
			"storm_ui_icon_zarya_particlegrenade",
			"storm_ui_icon_zarya_particlegrenade_a",
			"storm_ui_icon_zarya_personalbarrier"
		],
		[
			"storm_ui_icon_zarya_gravitonsurge",
			"storm_ui_icon_zarya_expulsionzone"
		],
		[
			"storm_ui_icon_zarya_personalbarrier",
			"storm_ui_icon_zarya_personalbarrier_a",
			"storm_ui_icon_zarya_energy",
			"storm_ui_icon_zarya_painistemporary"
		],
		[
			"storm_ui_icon_zarya_shieldally",
			"storm_ui_icon_zarya_shieldally_a",
			"storm_ui_icon_zarya_energy"
		],
		[
			"storm_ui_icon_zarya_gravitonsurge",
			"storm_ui_icon_zarya_expulsionzone",
			"storm_ui_icon_zarya_particlegrenade",
			"storm_ui_icon_zarya_unyieldingdefender"
		]
	],

	ragnaros:
	[
		[
			"storm_ui_icon_ragnaros_empowersulfuras",
			"storm_ui_icon_ragnaros_livingmeteor",
			"storm_ui_icon_ragnaros_blastwave"
		],
		[
			"storm_ui_icon_ragnaros_livingmeteor",
			"storm_ui_icon_ragnaros_blastwave",
			"storm_ui_icon_ragnaros_catchingfire"
		],
		[
			"storm_ui_icon_ragnaros_empowersulfuras",
			"storm_ui_icon_ragnaros_livingmeteor",
			"storm_ui_icon_talent_autoattack_damage"
		],
		[
			"storm_ui_icon_ragnaros_sulfurassmash",
			"storm_ui_icon_ragnaros_lavawave"
		],
		[
			"storm_ui_icon_ragnaros_empowersulfuras",
			"storm_ui_icon_ragnaros_blastwave",
			"storm_ui_icon_talent_resistance"
		],
		[
			"storm_ui_icon_ragnaros_empowersulfuras",
			"storm_ui_icon_ragnaros_livingmeteor",
			"storm_ui_icon_ragnaros_blastwave"
		],
		[
			"storm_ui_icon_ragnaros_sulfurassmash",
			"storm_ui_icon_ragnaros_lavawave",
			"storm_ui_icon_ragnaros_moltencore",
			"storm_ui_icon_ragnaros_submerge"
		]
	],

	kharazim:
	[
		[
			"storm_ui_icon_monk_trait_transcendence",
			"storm_ui_icon_monk_trait_ironfist",
			"storm_ui_icon_monk_trait_insight"
		],
		[
			"storm_ui_icon_monk_allyspirit",
			"storm_ui_icon_monk_allyearth",
			"storm_ui_icon_monk_allyair"
		],
		[
			"storm_ui_icon_monk_dash",
			"storm_ui_icon_monk_breath0fheaven",
			"storm_ui_icon_monk_deadlyreach"
		],
		[
			"storm_ui_icon_monk_divinepalm",
			"storm_ui_icon_monk_sevensidedstrike"
		],
		[
			"storm_ui_icon_monk_dash",
			"storm_ui_icon_talent_spellshield",
			"storm_ui_icon_talent_relentless"
		],
		[
			"storm_ui_icon_monk_dash",
			"storm_ui_icon_monk_dash_a",
			"storm_ui_icon_monk_breath0fheaven"
		],
		[
			"storm_ui_icon_monk_divinepalm",
			"storm_ui_icon_monk_sevensidedstrike",
			"storm_ui_icon_kharazim_fistoflegend",
			"storm_ui_icon_talent_stormshield",
			"storm_ui_icon_kharazim_epiphany"
		]
	],

	raynor:
	[
		[
			"storm_ui_icon_raynor_inspire",
			"storm_ui_icon_raynor_acquireweakspot",
			"storm_ui_icon_raynor_acardtoplay"
		],
		[
			"storm_ui_icon_raynor_adrenalinrush",
			"storm_ui_icon_raynor_acquireweakspot",
			"storm_ui_icon_raynor_hulkarmor"
		],
		[
			"storm_ui_icon_raynor_penetratinground",
			"storm_ui_icon_raynor_split_debilitatingrounds",
			"storm_ui_icon_raynor_acquireweakspot"
		],
		[
			"storm_ui_icon_raynor_hyperion",
			"storm_ui_icon_raynor_raynorsraiders"
		],
		[
			"storm_ui_icon_raynor_penetratinground",
			"storm_ui_icon_raynor_inspire",
			"storm_ui_icon_raynor_split_debilitatingrounds"
		],
		[
			"storm_ui_icon_raynor_penetratinground",
			"storm_ui_icon_raynor_inspire",
			"storm_ui_icon_raynor_acquireweakspot"
		],
		[
			"storm_ui_icon_raynor_hyperion",
			"storm_ui_icon_raynor_raynorsraiders",
			"storm_ui_icon_raynor_adrenalinrush",
			"storm_ui_icon_raynor_acquireweakspot",
			"storm_ui_icon_raynor_advancedoptics"
		]
	],

	zuljin:
	[
		[
			"storm_ui_icon_zuljin_grievousthrow",
			"storm_ui_icon_zuljin_berzerker",
			"storm_ui_icon_zuljin_headhunter"
		],
		[
			"storm_ui_icon_zuljin_regeneration",
			"storm_ui_icon_zuljin_regeneration_a",
			"storm_ui_icon_zuljin_davoodooshuffle"
		],
		[
			"storm_ui_icon_zuljin_grievousthrow",
			"storm_ui_icon_zuljin_twincleave",
			"storm_ui_icon_zuljin_berzerker"
		],
		[
			"storm_ui_icon_zuljin_tazdingo",
			"storm_ui_icon_zuljin_guillotine"
		],
		[
			"storm_ui_icon_zuljin_twincleave",
			"storm_ui_icon_talent_autoattack_base",
			"storm_ui_icon_zuljin_trollnet"
		],
		[
			"storm_ui_icon_zuljin_grievousthrow",
			"storm_ui_icon_zuljin_twincleave",
			"storm_ui_icon_talent_autoattack_speed"
		],
		[
			"storm_ui_icon_zuljin_tazdingo",
			"storm_ui_icon_zuljin_guillotine",
			"storm_ui_icon_zuljin_regeneration",
			"storm_ui_icon_talent_autoattack_aoe"
		]
	],

	mei:
	[
		[
			"storm_ui_icon_mei_q_snowblind",
			"storm_ui_icon_mei_w_blizzard",
			"storm_ui_icon_talent_autoattack_damage"
		],
		[
			"storm_ui_icon_mei_q_snowblind",
			"storm_ui_icon_mei_e1_slide",
			"storm_ui_icon_mei_trait"
		],
		[
			"storm_ui_icon_mei_w_blizzard",
			"storm_ui_icon_mei_e1_slide",
			"storm_ui_icon_mei_battery"
		],
		[
			"storm_ui_icon_mei_r1_avalanche",
			"storm_ui_icon_mei_r2_icewall"
		],
		[
			"storm_ui_icon_mei_w_blizzard",
			"storm_ui_icon_mei_trait",
			"storm_ui_icon_arthas_frosentempest"
		],
		[
			"storm_ui_icon_mei_q_snowblind",
			"storm_ui_icon_mei_e1_slide",
			"storm_ui_icon_jaina_frostarmor"
		],
		[
			"storm_ui_icon_mei_r1_avalanche",
			"storm_ui_icon_mei_r2_icewall",
			"storm_ui_icon_mei_q_snowblind",
			"storm_ui_icon_mei_trait"
		]
	],

	brightwing:
	[
		[
			"storm_ui_icon_brightwing_polymorph",
			"storm_ui_icon_brightwing_hypershift",
			"storm_ui_icon_talent_bribe"
		],
		[
			"storm_ui_icon_brightwing_arcaneflare",
			"storm_ui_icon_brightwing_polymorph",
			"storm_ui_icon_talent_autoattack_cooldown"
		],
		[
			"storm_ui_icon_brightwing_arcaneflare",
			"storm_ui_icon_brightwing_hypershift",
			"storm_ui_icon_brightwing_soothingmist"
		],
		[
			"storm_ui_icon_brightwing_blinkheal",
			"storm_ui_icon_brightwing_emeraldwind"
		],
		[
			"storm_ui_icon_brightwing_pixiedust",
			"storm_ui_icon_brightwing_pixiedust_a",
			"storm_ui_icon_brightwing_pixiedust_b"
		],
		[
			"storm_ui_icon_brightwing_arcaneflare",
			"storm_ui_icon_brightwing_polymorph",
			"storm_ui_icon_brightwing_stasis"
		],
		[
			"storm_ui_icon_brightwing_blinkheal",
			"storm_ui_icon_brightwing_emeraldwind",
			"storm_ui_icon_brightwing_hypershift",
			"storm_ui_icon_brightwing_pixiedust"
		]
	],

	ltmorales:
	[
		[
			"storm_ui_icon_talent_autoattack_mana",
			"storm_ui_icon_medic_healingbeam",
			"storm_ui_icon_medic_displacementgrenade"
		],
		[
			"storm_temp_btnupgradeterranmobiusreactor",
			"storm_ui_icon_medic_advancedblock",
			"storm_ui_icon_medic_displacementgrenade"
		],
		[
			"storm_ui_icon_medic_deployshield",
			"storm_ui_icon_medic_deployshield_c",
			"storm_ui_icon_medic_deployshield_b"
		],
		[
			"storm_ui_icon_medic_stim",
			"storm_ui_icon_medic_medivacdropship"
		],
		[
			"storm_ui_icon_medic_displacementgrenade",
			"storm_ui_icon_medic_displacementgrenade_b",
			"storm_ui_icon_medic_displacementgrenade_c"
		],
		[
			"storm_ui_icon_medic_healingbeam",
			"storm_ui_icon_medic_healingbeam_c",
			"storm_ui_icon_medic_deployshield"
		],
		[
			"storm_ui_icon_medic_stim",
			"storm_ui_icon_medic_medivacdropship",
			"storm_ui_icon_medic_deployshield",
			"storm_ui_icon_medic_displacementgrenade"
		]
	],

	guldan:
	[
		[
			"storm_ui_icon_guldan_felflame",
			"storm_ui_icon_guldan_healthfunnel",
			"storm_ui_icon_guldan_handofguldan"
		],
		[
			"storm_ui_icon_guldan_healthfunnel",
			"storm_ui_icon_guldan_lifetap",
			"storm_ui_icon_guldan_darkpact"
		],
		[
			"storm_ui_icon_guldan_felflame",
			"storm_ui_icon_guldan_healthfunnel",
			"storm_ui_icon_guldan_hungerforpower"
		],
		[
			"storm_ui_icon_guldan_horrify",
			"storm_ui_icon_guldan_rainoffire"
		],
		[
			"storm_ui_icon_guldan_felflame",
			"storm_ui_icon_guldan_healthfunnel",
			"storm_ui_icon_guldan_darkbargain",
			"storm_ui_icon_guldan_healthstone"
		],
		[
			"storm_ui_icon_guldan_felflame",
			"storm_ui_icon_guldan_handofguldan",
			"storm_ui_icon_guldan_lifetap"
		],
		[
			"storm_ui_icon_guldan_horrify",
			"storm_ui_icon_guldan_rainoffire",
			"storm_ui_icon_guldan_demoniccircle"
		]
	],

	fenix:
	[
		[
			"storm_ui_icon_fenix_q",
			"storm_ui_icon_fenix_w_1",
			"storm_ui_icon_fenix_w_2"
		],
		[
			"storm_ui_icon_fenix_w_2",
			"storm_ui_icon_fenix_w_1",
			"storm_ui_icon_fenix_shield_1"
		],
		[
			"storm_ui_icon_fenix_q",
			"storm_ui_icon_fenix_teleport",
			"storm_ui_icon_fenix_w_2"
		],
		[
			"storm_ui_icon_fenix_r_scan",
			"storm_ui_icon_fenix_r_planet_cracker"
		],
		[
			"storm_ui_icon_fenix_teleport",
			"storm_ui_icon_fenix_shield_1",
			"storm_ui_icon_fenix_shield_3",
			"storm_ui_icon_fenix_shield_2"
		],
		[
			"storm_ui_icon_fenix_w_2",
			"storm_ui_icon_fenix_shield_1",
			"storm_ui_icon_talent_autoattack_cooldown"
		],
		[
			"storm_ui_icon_fenix_r_planet_cracker",
			"storm_ui_icon_fenix_q",
			"storm_ui_icon_fenix_w_2",
			"storm_ui_icon_fenix_shield_1"
		]
	],

	blaze:
	[
		[
			"storm_ui_icon_blaze_stim_2",
			"storm_ui_icon_blaze_stim_1",
			"storm_ui_icon_blaze_stim_3",
			"storm_ui_icon_blaze_new_habits"
		],
		[
			"storm_ui_icon_blaze_oil",
			"storm_ui_icon_blaze_pyromania",
			"storm_ui_icon_talent_autoattack_slow"
		],
		[
			"storm_ui_icon_blaze_flame",
			"storm_ui_icon_blaze_oil",
			"storm_ui_icon_blaze_jet"
		],
		[
			"storm_ui_icon_blaze_bunker",
			"storm_ui_icon_blaze_combustion"
		],
		[
			"storm_ui_icon_blaze_oil",
			"storm_ui_icon_blaze_oil_b",
			"storm_ui_icon_blaze_jet"
		],
		[
			"storm_ui_icon_blaze_jet",
			"storm_ui_icon_blaze_pyromania",
			"storm_ui_icon_blaze_vanadium_plating"
		],
		[
			"storm_ui_icon_blaze_bunker",
			"storm_ui_icon_blaze_combustion",
			"storm_ui_icon_talent_autoattack_slow"
		]
	],

	cassia:
	[
		[
			"storm_ui_icon_cassia_lightningfury",
			"storm_ui_icon_cassia_fend",
			"storm_ui_icon_cassia_new_chargedstrikes"
		],
		[
			"storm_ui_icon_cassia_avoidance_b",
			"storm_ui_icon_cassia_ringoftheleech",
			"storm_ui_icon_cassia_innerlight"
		],
		[
			"storm_ui_icon_cassia_combo_q_e",
			"storm_ui_icon_cassia_blindinglight",
			"storm_ui_icon_cassia_avoidance_b"
		],
		[
			"storm_ui_icon_cassia_balllightning",
			"storm_ui_icon_cassia_valkrie"
		],
		[
			"storm_ui_icon_cassia_fend",
			"storm_ui_icon_cassia_avoidance_b",
			"storm_ui_icon_cassia_new_gloves"
		],
		[
			"storm_ui_icon_cassia_combo_q_w",
			"storm_ui_icon_cassia_combo_q_e",
			"storm_ui_icon_talent_autoattack_damage"
		],
		[
			"storm_ui_icon_cassia_balllightning_a",
			"storm_ui_icon_cassia_valkrie_a",
			"storm_ui_icon_cassia_avoidance_b",
			"storm_ui_icon_cassia_avoidance"
		]
	],

	tracer:
	[
		[
			"storm_ui_icon_tracer_melee",
			"storm_ui_icon_tracer_combo_e_r",
			"storm_ui_icon_tracer_reload"
		],
		[
			"storm_ui_icon_tracer_reload",
			"storm_ui_icon_tracer_combo_q_r",
			"storm_ui_icon_tracer_medpack"
		],
		[
			"storm_ui_icon_tracer_reload",
			"storm_ui_icon_tracer_reload_b",
			"storm_ui_icon_tracer_reload_c"
		],
		[
			"storm_ui_icon_tracer_pulsebomb",
			"storm_ui_icon_tracer_pulsebomb_b",
			"storm_ui_icon_tracer_pulsebomb_c"
		],
		[
			"storm_ui_icon_tracer_combo_q_trait",
			"storm_ui_icon_tracer_blink_d",
			"storm_ui_icon_tracer_recall"
		],
		[
			"storm_ui_icon_tracer_melee",
			"storm_ui_icon_tracer_melee_b",
			"storm_ui_icon_tracer_reload"
		],
		[
			"storm_ui_icon_tracer_combo_q_trait",
			"storm_ui_icon_tracer_melee",
			"storm_ui_icon_tracer_recall",
			"storm_ui_icon_tracer_pulsebomb"
		]
	],

	anduin:
	[
		[
			"storm_ui_icon_anduin_flash_heal",
			"storm_ui_icon_anduin_divine_star",
			"storm_ui_icon_anduin_lightwell"
		],
		[
			"storm_ui_icon_anduin_divine_star",
			"storm_ui_icon_anduin_chastise",
			"storm_ui_icon_anduin_chastise_a"
		],
		[
			"storm_ui_icon_anduin_flash_heal",
			"storm_ui_icon_anduin_blessed_recovery",
			"storm_ui_icon_anduin_desperate_prayer"
		],
		[
			"storm_ui_icon_anduin_holy_word_salvation",
			"storm_ui_icon_anduin_light_bomb"
		],
		[
			"storm_ui_icon_anduin_divine_star",
			"storm_ui_icon_anduin_varians_legacy",
			"storm_ui_icon_anduin_leap_of_faith"
		],
		[
			"storm_ui_icon_anduin_flash_heal",
			"storm_ui_icon_anduin_divine_star",
			"storm_ui_icon_anduin_leap_of_faith",
			"storm_ui_icon_anduin_inner_focus"
		],
		[
			"storm_ui_icon_anduin_holy_word_salvation",
			"storm_ui_icon_anduin_light_bomb",
			"storm_ui_icon_anduin_chastise",
			"storm_ui_icon_anduin_varians_legacy"
		]
	],

	abathur:
	[
		[
			"storm_ui_icon_abathur_spikeburst",
			"storm_ui_icon_abathur_toxicnest",
			"storm_ui_icon_abathur_carapace",
			"storm_ui_icon_abathur_spawnlocust"
		],
		[
			"storm_ui_icon_abathur_symbiote",
			"storm_ui_icon_abathur_stab",
			"storm_ui_icon_abathur_toxicnest"
		],
		[
			"storm_ui_icon_abathur_toxicnest",
			"storm_ui_icon_abathur_carapace",
			"storm_ui_icon_talent_mule"
		],
		[
			"storm_ui_icon_abathur_ultimateevolution",
			"storm_ui_icon_abathur_evolvemonstrosity"
		],
		[
			"storm_ui_icon_abathur_stab",
			"storm_ui_icon_abathur_spikeburst",
			"storm_ui_icon_abathur_spawnlocust_var1"
		],
		[
			"storm_ui_icon_abathur_spikeburst",
			"storm_ui_icon_abathur_carapace",
			"storm_ui_icon_abathur_volatilemutation",
			"storm_ui_icon_abathur_spawnlocust"
		],
		[
			"storm_ui_icon_abathur_ultimateevolution",
			"storm_ui_icon_abathur_evolvemonstrosity",
			"storm_ui_icon_abathur_symbiote",
			"storm_ui_icon_abathur_locustnest"
		]
	],

	whitemane:
	[
		[
			"storm_ui_icon_whitemane_inquisition_lash",
			"storm_ui_icon_whitemane_lash",
			"storm_ui_icon_whitemane_lash_alt_1"
		],
		[
			"storm_ui_icon_whitemane_desperation",
			"storm_ui_icon_whitemane_desperation_alt_1",
			"storm_ui_icon_whitemane_zeal"
		],
		[
			"storm_ui_icon_whitemane_desperation",
			"storm_ui_icon_whitemane_lash_alt_1",
			"storm_ui_icon_whitemane_intercession"
		],
		[
			"storm_ui_icon_whitemane_aegis",
			"storm_ui_icon_whitemane_reckoning"
		],
		[
			"storm_ui_icon_whitemane_inquisition",
			"storm_ui_icon_whitemane_lash",
			"storm_ui_icon_whitemane_zeal"
		],
		[
			"storm_ui_icon_whitemane_desperation",
			"storm_ui_icon_whitemane_inquisition",
			"storm_ui_icon_whitemane_lash"
		],
		[
			"storm_ui_icon_whitemane_aegis",
			"storm_ui_icon_whitemane_reckoning",
			"storm_ui_icon_whitemane_zeal",
			"storm_ui_icon_whitemane_purge"
		]
	],

	kaelthas:
	[
		[
			"storm_ui_icon_kaelthas_flamestrike",
			"storm_ui_icon_kaelthas_verdantspheres",
			"storm_ui_icon_kaelthas_manaaddict"
		],
		[
			"storm_ui_icon_kaelthas_gravitylapse",
			"storm_ui_icon_kaelthas_gravitylapse_a",
			"storm_ui_icon_kaelthas_verdantspheres"
		],
		[
			"storm_ui_icon_kaelthas_flamestrike",
			"storm_ui_icon_kaelthas_livingbomb",
			"storm_ui_icon_kaelthas_verdantspheres"
		],
		[
			"storm_ui_icon_kaelthas_phoenix",
			"storm_ui_icon_kaelthas_pyroblast"
		],
		[
			"storm_ui_icon_kaelthas_livingbomb",
			"storm_ui_icon_kaelthas_livingbomb_var1",
			"storm_ui_icon_kaelthas_livingbomb_b"
		],
		[
			"storm_ui_icon_kaelthas_flamestrike",
			"storm_ui_icon_kaelthas_livingbomb",
			"storm_ui_icon_kaelthas_verdantspheres"
		],
		[
			"storm_ui_icon_kaelthas_phoenix",
			"storm_ui_icon_kaelthas_pyroblast",
			"storm_ui_icon_kaelthas_livingbomb",
			"storm_ui_icon_kaelthas_flamestrike"
		]
	],

	kerrigan:
	[
		[
			"storm_ui_icon_kerrigan_ravage",
			"storm_ui_icon_kerrigan_assimilation",
			"storm_ui_icon_talent_autoattack_aoe"
		],
		[
			"storm_ui_icon_kerrigan_ravage",
			"storm_ui_icon_kerrigan_impalingblades",
			"storm_ui_icon_kerrigan_primalgrasp"
		],
		[
			"storm_ui_icon_kerrigan_ravage",
			"storm_ui_icon_kerrigan_ravage_b",
			"storm_ui_icon_talent_autoattack_cooldown"
		],
		[
			"storm_ui_icon_kerrigan_maelstrom",
			"storm_ui_icon_kerrigan_ultralisk"
		],
		[
			"storm_ui_icon_kerrigan_primalgrasp",
			"storm_ui_icon_kerrigan_assimilation",
			"storm_ui_icon_kerrigan_chrysalis"
		],
		[
			"storm_ui_icon_kerrigan_ravage",
			"storm_ui_icon_kerrigan_impalingblades",
			"storm_ui_icon_talent_abilitytalent_damage"
		],
		[
			"storm_ui_icon_kerrigan_maelstrom",
			"storm_ui_icon_kerrigan_ultralisk",
			"storm_ui_icon_talent_autoattack_damage",
			"storm_ui_icon_talent_boltofthestorm"
		]
	],

	lili:
	[
		[
			"storm_ui_icon_lili_healingbrew",
			"storm_ui_icon_lili_cloudserpent",
			"storm_ui_icon_lili_fastfeet"
		],
		[
			"storm_ui_icon_lili_cloudserpent",
			"storm_ui_icon_lili_blindingwind",
			"storm_ui_icon_lili_fastfeet"
		],
		[
			"storm_ui_icon_lili_healingbrew",
			"storm_ui_icon_lili_blindingwind",
			"storm_ui_icon_talent_cleanse"
		],
		[
			"storm_ui_icon_lili_jugofathousandcups",
			"storm_ui_icon_lili_waterdragon"
		],
		[
			"storm_ui_icon_lili_cloudserpent",
			"storm_ui_icon_lili_blindingwind",
			"storm_ui_icon_lili_blindingwind_a"
		],
		[
			"storm_ui_icon_lili_healingbrew",
			"storm_ui_icon_lili_healingbrew_a",
			"storm_ui_icon_lili_cloudserpent"
		],
		[
			"storm_ui_icon_lili_jugofathousandcups",
			"storm_ui_icon_lili_waterdragon",
			"storm_ui_icon_lili_mistweaver",
			"storm_ui_icon_lili_fastfeet"
		]
	],

	stitches:
	[
		[
			"storm_ui_icon_stitches_patchwork",
			"storm_ui_icon_stitches_devour",
			"storm_ui_icon_stitches_hungry"
		],
		[
			"storm_ui_icon_stitches_slam",
			"storm_ui_icon_stitches_acidcloud",
			"storm_ui_icon_talent_autoattack_slow"
		],
		[
			"storm_ui_icon_stitches_hook",
			"storm_ui_icon_stitches_devour",
			"storm_ui_icon_stitches_acidcloud"
		],
		[
			"storm_ui_icon_stitches_putridbile",
			"storm_ui_icon_stitches_cannibalize"
		],
		[
			"storm_ui_icon_stitches_hook",
			"storm_ui_icon_stitches_underpressure",
			"storm_ui_icon_stitches_chopchop"
		],
		[
			"storm_ui_icon_stitches_slam",
			"storm_ui_icon_stitches_devour",
			"storm_ui_icon_talent_burningrage"
		],
		[
			"storm_ui_icon_stitches_putridbile",
			"storm_ui_icon_stitches_cannibalize",
			"storm_ui_icon_stitches_hook",
			"storm_ui_icon_stitches_acidcloud"
		]
	],

	chromie:
	[
		[
			"storm_ui_icon_chromie_aethercannon",
			"storm_ui_icon_chromie_sandstrike",
			"storm_ui_icon_talent_clairvoyance"
		],
		[
			"storm_ui_icon_chromie_timetrap",
			"storm_ui_icon_chromie_timetrap_a",
			"storm_ui_icon_chromie_timetrap_b"
		],
		[
			"storm_ui_icon_chromie_aethercannon",
			"storm_ui_icon_chromie_sandstrike",
			"storm_ui_icon_talent_abilitytalent_damage"
		],
		[
			"storm_ui_icon_chromie_timewarp",
			"storm_ui_icon_chromie_looper"
		],
		[
			"storm_ui_icon_chromie_aethercannon",
			"storm_ui_icon_chromie_herethere",
			"storm_ui_icon_chromie_timeblock"
		],
		[
			"storm_ui_icon_chromie_aethercannon",
			"storm_ui_icon_chromie_aethercannon_a",
			"storm_ui_icon_chromie_hyperdrivesreach"
		],
		[
			"storm_ui_icon_chromie_timewarp",
			"storm_ui_icon_chromie_looper",
			"storm_ui_icon_chromie_aethercannon",
			"storm_ui_icon_chromie_blessing_of_the_bronze"
		]
	],

	sonya:
	[
		[
			"storm_ui_icon_sonya_seismicslam",
			"storm_ui_icon_talent_autoattack_heal",
			"storm_ui_icon_talent_block"
		],
		[
			"storm_ui_icon_sonya_seismicslam",
			"storm_ui_icon_sonya_whirlwind",
			"storm_ui_icon_sonya_fury"
		],
		[
			"storm_ui_icon_sonya_ancientspear",
			"storm_ui_icon_sonya_whirlwind",
			"storm_ui_icon_talent_mercenarylord"
		],
		[
			"storm_ui_icon_sonya_leap",
			"storm_ui_icon_sonya_wrathoftheberserker"
		],
		[
			"storm_ui_icon_sonya_ancientspear",
			"storm_ui_icon_sonya_whirlwind",
			"storm_ui_icon_sonya_fury"
		],
		[
			"storm_ui_icon_sonya_seismicslam",
			"storm_ui_icon_talent_autoattack_damage",
			"storm_ui_icon_sonya_nervesofsteel"
		],
		[
			"storm_ui_icon_sonya_leap",
			"storm_ui_icon_sonya_wrathoftheberserker",
			"storm_ui_icon_sonya_ancientspear",
			"storm_ui_icon_sonya_ignorepain"
		]
	],

	tyrande:
	[
		[
			"storm_ui_icon_tyrande_sentinel",
			"storm_ui_icon_tyrande_lunarflare",
			"storm_ui_icon_tyrande_trueshotaura"
		],
		[
			"storm_ui_icon_tyrande_lightofelune",
			"storm_ui_icon_tyrande_huntersmark",
			"storm_ui_icon_talent_autoattack_heal"
		],
		[
			"storm_ui_icon_tyrande_lightofelune",
			"storm_ui_icon_tyrande_lightofelune_a",
			"storm_ui_icon_tyrande_huntersmark"
		],
		[
			"storm_ui_icon_tyrande_shadowstalk",
			"storm_ui_icon_tyrande_starfall"
		],
		[
			"storm_ui_icon_tyrande_lightofelune",
			"storm_ui_icon_tyrande_sentinel",
			"storm_ui_icon_tyrande_huntersmark"
		],
		[
			"storm_ui_icon_tyrande_lightofelune",
			"storm_ui_icon_tyrande_sentinel",
			"storm_ui_icon_talent_autoattack_damage"
		],
		[
			"storm_ui_icon_tyrande_shadowstalk",
			"storm_ui_icon_tyrande_starfall",
			"storm_ui_icon_talent_autoattack_speed",
			"storm_ui_icon_talent_autoattack_slow"
		]
	],

	junkrat:
	[
		[
			"storm_ui_icon_junkrat_frag_launcher",
			"storm_ui_icon_junkrat_frag_launcher_b",
			"storm_ui_icon_junkrat_trap_mine"
		],
		[
			"storm_ui_icon_junkrat_frag_launcher",
			"storm_ui_icon_junkrat_concussion_mine",
			"storm_ui_icon_junkrat_steel_trap"
		],
		[
			"storm_ui_icon_junkrat_concussion_mine",
			"storm_ui_icon_junkrat_steel_trap",
			"storm_ui_icon_junkrat_bomb_pack"
		],
		[
			"storm_ui_icon_junkrat_rip_tire",
			"storm_ui_icon_junkrat_rocket_ride"
		],
		[
			"storm_ui_icon_junkrat_frag_launcher",
			"storm_ui_icon_junkrat_concussion_mine",
			"storm_ui_icon_junkrat_steel_trap",
			"storm_ui_icon_junkrat_steel_trap_a"
		],
		[
			"storm_ui_icon_junkrat_frag_launcher_f",
			"storm_ui_icon_junkrat_frag_launcher_e",
			"storm_ui_icon_junkrat_frag_launcher_d"
		],
		[
			"storm_ui_icon_junkrat_rip_tire",
			"storm_ui_icon_junkrat_rocket_ride",
			"storm_ui_icon_junkrat_frag_launcher_g",
			"storm_ui_icon_junkrat_mount_rocket"
		]
	],

	qhira:
	[
		[
			"storm_ui_icon_nexushunter_q",
			"storm_ui_icon_nexushunter_w",
			"storm_ui_icon_nexushunter_passive"
		],
		[
			"storm_ui_icon_nexushunter_w",
			"storm_ui_icon_nexushunter_e",
			"storm_ui_icon_nexushunter_passive"
		],
		[
			"storm_ui_icon_nexushunter_q",
			"storm_ui_icon_nexushunter_w",
			"storm_ui_icon_nexushunter_e"
		],
		[
			"storm_ui_icon_nexushunter_r1",
			"storm_ui_icon_nexushunter_r2"
		],
		[
			"storm_ui_icon_nexushunter_q",
			"storm_ui_icon_nexushunter_e",
			"storm_ui_icon_nexushunter_passive"
		],
		[
			"storm_ui_icon_nexushunter_e",
			"storm_ui_icon_nexushunter_e_alt_1",
			"storm_ui_icon_nexushunter_e_alt_2"
		],
		[
			"storm_ui_icon_nexushunter_r1",
			"storm_ui_icon_nexushunter_r2",
			"storm_ui_icon_nexushunter_d",
			"storm_ui_icon_nexushunter_passive_alt_1"
		]
	],

	xul:
	[
		[
			"storm_ui_icon_necromancer_bonearmor_b",
			"storm_ui_icon_necromancer_bonearmor_c",
			"storm_ui_icon_necromancer_bonearmor"
		],
		[
			"storm_ui_icon_necromancer_reap",
			"storm_ui_icon_necromancer_cursedstrikes_off",
			"storm_ui_icon_necromancer_raiseskeleton"
		],
		[
			"storm_ui_icon_necromancer_cursedstrikes_off",
			"storm_ui_icon_necromancer_raiseskeleton",
			"storm_ui_icon_necromancer_bonearmor"
		],
		[
			"storm_ui_icon_necromancer_poisonnova",
			"storm_ui_icon_necromancer_skeletalmages"
		],
		[
			"storm_ui_icon_necromancer_reap",
			"storm_ui_icon_necromancer_cursedstrikes_off",
			"storm_ui_icon_necromancer_boneprison"
		],
		[
			"storm_ui_icon_necromancer_reap",
			"storm_ui_icon_necromancer_cursedstrikes_off",
			"storm_ui_icon_necromancer_bonespear"
		],
		[
			"storm_ui_icon_necromancer_poisonnova",
			"storm_ui_icon_necromancer_skeletalmages",
			"storm_ui_icon_necromancer_reap",
			"storm_ui_icon_necromancer_raiseskeleton"
		]
	],

	mephisto:
	[
		[
			"storm_ui_icon_mephisto_skull",
			"storm_ui_icon_mephisto_lightning",
			"storm_ui_icon_mephisto_shade"
		],
		[
			"storm_ui_icon_mephisto_skull",
			"storm_ui_icon_mephisto_lightning",
			"storm_ui_icon_mephisto_hatred"
		],
		[
			"storm_ui_icon_mephisto_shade",
			"storm_ui_icon_mephisto_shade_b",
			"storm_ui_icon_mephisto_shade_c"
		],
		[
			"storm_ui_icon_mephisto_souls",
			"storm_ui_icon_mephisto_durance"
		],
		[
			"storm_ui_icon_mephisto_skull",
			"storm_ui_icon_mephisto_hatred",
			"storm_ui_icon_mephisto_splash"
		],
		[
			"storm_ui_icon_mephisto_skull",
			"storm_ui_icon_mephisto_lightning",
			"storm_ui_icon_mephisto_lightning_b"
		],
		[
			"storm_ui_icon_mephisto_souls",
			"storm_ui_icon_mephisto_durance",
			"storm_ui_icon_mephisto_lightning",
			"storm_ui_icon_mephisto_shade"
		]
	],

	tyrael:
	[
		[
			"storm_ui_icon_tyrael_righteousness",
			"storm_ui_icon_tyrael_righteousness_var1",
			"storm_ui_icon_talent_regenerationmaster"
		],
		[
			"storm_ui_icon_tyrael_eldruinsmight_a",
			"storm_ui_icon_tyrael_eldruinsmight_b",
			"storm_ui_icon_tyrael_smite"
		],
		[
			"storm_ui_icon_tyrael_righteousness",
			"storm_ui_icon_tyrael_smite",
			"storm_ui_icon_tyrael_smite_a"
		],
		[
			"storm_ui_icon_tyrael_judgement",
			"storm_ui_icon_tyrael_sanctification"
		],
		[
			"storm_ui_icon_tyrael_eldruinsmight_a",
			"storm_ui_icon_tyrael_eldruinsmight_b",
			"storm_ui_icon_tyrael_zealous_conviction"
		],
		[
			"storm_ui_icon_tyrael_eldruinsmight_a",
			"storm_ui_icon_tyrael_eldruinsmight_b",
			"storm_ui_icon_tyrael_smite"
		],
		[
			"storm_ui_icon_tyrael_judgement",
			"storm_ui_icon_tyrael_sanctification",
			"storm_ui_icon_talent_autoattack_speed",
			"storm_ui_icon_talent_hardenedshield"
		]
	],

	muradin:
	[
		[
			"storm_ui_icon_muradin_stormbolt",
			"storm_ui_icon_muradin_dwarftoss",
			"storm_ui_icon_muradin_secondwind"
		],
		[
			"storm_ui_icon_muradin_stormbolt",
			"storm_ui_icon_muradin_thunderclap",
			"storm_ui_icon_muradin_thunderclap_b"
		],
		[
			"storm_ui_icon_muradin_dwarftoss",
			"storm_ui_icon_talent_autoattack_damage",
			"storm_ui_icon_talent_autoattack_stun"
		],
		[
			"storm_ui_icon_muradin_avatar",
			"storm_ui_icon_muradin_haymaker"
		],
		[
			"storm_ui_icon_talent_burningrage",
			"storm_ui_icon_muradin_thunderclap_a",
			"storm_ui_icon_muradin_thunderclap"
		],
		[
			"storm_ui_icon_muradin_dwarftoss",
			"storm_ui_icon_talent_imposingpresence",
			"storm_ui_icon_muradin_secondwind"
		],
		[
			"storm_ui_icon_muradin_avatar",
			"storm_ui_icon_muradin_haymaker",
			"storm_ui_icon_talent_hardenedshield",
			"storm_ui_icon_talent_rewind"
		]
	],

	anubarak:
	[
		[
			"storm_ui_icon_anubarak_hardencarapace_var1",
			"storm_ui_icon_anubarak_scarabhost",
			"storm_ui_icon_talent_regenerationmaster"
		],
		[
			"storm_ui_icon_anubarak_impale",
			"storm_ui_icon_anubarak_hardencarapace_var1",
			"storm_ui_icon_anubarak_burrowcharge"
		],
		[
			"storm_ui_icon_anubarak_hardencarapace_var2",
			"storm_ui_icon_anubarak_burrowcharge",
			"storm_ui_icon_anubarak_scarabhost"
		],
		[
			"storm_ui_icon_anubarak_locustswarm",
			"storm_ui_icon_anubarak_webblast"
		],
		[
			"storm_ui_icon_anubarak_hardencarapace_var1",
			"storm_ui_icon_talent_burningrage",
			"storm_ui_icon_talent_autoattack_damage"
		],
		[
			"storm_ui_icon_anubarak_burrowcharge",
			"storm_ui_icon_anubarak_combo_q_e",
			"storm_ui_icon_anubarak_scarabhost"
		],
		[
			"storm_ui_icon_anubarak_locustswarm",
			"storm_ui_icon_anubarak_webblast",
			"storm_ui_glues_draft_portrait_anubarak",
			"storm_ui_icon_talent_rewind"
		]
	],

	alexstrasza:
	[
		[
			"storm_ui_icon_alexstrasza_gift_of_life",
			"storm_ui_icon_alexstrasza_abundance",
			"storm_ui_icon_alexstrasza_flame_buffet"
		],
		[
			"storm_ui_icon_alexstrasza_abundance",
			"storm_ui_icon_alexstrasza_flame_buffet",
			"storm_ui_icon_alexstrasza_exuberance"
		],
		[
			"storm_ui_icon_alexstrasza_life_blossom",
			"storm_ui_icon_alexstrasza_abundance",
			"storm_ui_icon_alexstrasza_flame_buffet"
		],
		[
			"storm_ui_icon_alexstrasza_life_binder",
			"storm_ui_icon_alexstrasza_cleansing_flame"
		],
		[
			"storm_ui_icon_alexstrasza_dragon_scales",
			"storm_ui_icon_alexstrasza_pacify",
			"storm_ui_icon_alexstrasza_life_unbound"
		],
		[
			"storm_ui_icon_alexstrasza_gift_of_life",
			"storm_ui_icon_alexstrasza_abundance",
			"storm_ui_icon_alexstrasza_dragon_queen"
		],
		[
			"storm_ui_icon_alexstrasza_life_binder",
			"storm_ui_icon_alexstrasza_cleansing_flame",
			"storm_ui_icon_alexstrasza_dragon_queen_a",
			"storm_ui_icon_alexstrasza_blessing_of_the_red"
		]
	],

	greymane:
	[
		[
			"storm_ui_icon_greymane_beastfocus",
			"storm_ui_icon_greymane_qattack",
			"storm_ui_icon_greymane_beastfocus_var1"
		],
		[
			"storm_ui_icon_greymane_darkflight",
			"storm_ui_icon_greymane_disengage",
			"storm_ui_icon_greymane_beastfocus"
		],
		[
			"storm_ui_icon_greymane_curseoftheworgen",
			"storm_ui_icon_greymane_qattack",
			"storm_ui_icon_greymane_curseoftheworgen_var1"
		],
		[
			"storm_ui_icon_greymane_goforthethroat",
			"storm_ui_icon_greymane_snapshot"
		],
		[
			"storm_ui_icon_greymane_darkflight",
			"storm_ui_icon_greymane_swipe",
			"storm_ui_icon_greymane_beastfocus"
		],
		[
			"storm_ui_icon_greymane_beastfocus",
			"storm_ui_icon_talent_autoattack_damage",
			"storm_ui_icon_greymane_curseoftheworgen_var1"
		],
		[
			"storm_ui_icon_greymane_goforthethroat",
			"storm_ui_icon_greymane_snapshot",
			"storm_ui_icon_greymane_curseoftheworgen",
			"storm_ui_icon_greymane_curseoftheworgen_var1"
		]
	],

	tychus:
	[
		[
			"storm_ui_icon_tychus_fraggrenade",
			"storm_ui_icon_tychus_runandgun",
			"storm_ui_icon_talent_autoattack_range"
		],
		[
			"storm_ui_icon_tychus_minigun",
			"storm_ui_icon_tychus_minigun_a",
			"storm_ui_icon_talent_autoattack_speed"
		],
		[
			"storm_ui_icon_tychus_fraggrenade",
			"storm_ui_icon_tychus_minigun",
			"storm_ui_icon_talent_relentless"
		],
		[
			"storm_ui_icon_tychus_commandeerodin",
			"storm_ui_icon_tychus_drakkinlaserdrill"
		],
		[
			"storm_ui_icon_tychus_overkill",
			"storm_ui_icon_tychus_minigun",
			"storm_temp_btnupgradeterranneosteelframe"
		],
		[
			"storm_ui_icon_tychus_overkill",
			"storm_ui_icon_tychus_fraggrenade",
			"storm_ui_icon_talent_autoattack_damage"
		],
		[
			"storm_ui_icon_tychus_commandeerodin",
			"storm_ui_icon_tychus_drakkinlaserdrill",
			"storm_ui_icon_tychus_overkill",
			"storm_ui_icon_tychus_runandgun"
		]
	],

	imperius:
	[
		[
			"storm_ui_icon_imperius_q",
			"storm_ui_icon_imperius_w",
			"storm_ui_icon_imperius_trait"
		],
		[
			"storm_ui_icon_imperius_e",
			"storm_ui_icon_imperius_trait",
			"storm_ui_icon_imperius_globe"
		],
		[
			"storm_ui_icon_imperius_q",
			"storm_ui_icon_imperius_w",
			"storm_ui_icon_imperius_item_01"
		],
		[
			"storm_ui_icon_imperius_r1",
			"storm_ui_icon_imperius_r2"
		],
		[
			"storm_ui_icon_imperius_q",
			"storm_ui_icon_imperius_e",
			"storm_ui_icon_imperius_e_alt_01"
		],
		[
			"storm_ui_icon_imperius_q",
			"storm_ui_icon_imperius_e",
			"storm_ui_icon_imperius_item_03"
		],
		[
			"storm_ui_icon_imperius_r1",
			"storm_ui_icon_imperius_r2",
			"storm_ui_icon_imperius_trait",
			"storm_ui_icon_imperius_item_02"
		]
	],

	garrosh:
	[
		[
			"storm_ui_icon_garrosh_groundbreaker",
			"storm_ui_icon_garrosh_wrecking_ball",
			"storm_ui_icon_garrosh_slam"
		],
		[
			"storm_ui_icon_garrosh_bloodthirst",
			"storm_ui_icon_garrosh_bloodthirst_var1",
			"storm_ui_icon_garrosh_indomitablel"
		],
		[
			"storm_ui_icon_garrosh_groundbreaker",
			"storm_ui_icon_garrosh_bloodthirst",
			"storm_ui_icon_garrosh_intothefray"
		],
		[
			"storm_ui_icon_garrosh_warlords_challenge",
			"storm_ui_icon_garrosh_decimate"
		],
		[
			"storm_ui_icon_garrosh_groundbreaker",
			"storm_ui_icon_garrosh_bloodthirst",
			"storm_ui_icon_garrosh_armor_up"
		],
		[
			"storm_ui_icon_garrosh_wrecking_ball",
			"storm_ui_icon_garrosh_intothefray",
			"storm_ui_icon_garrosh_armor_up"
		],
		[
			"storm_ui_icon_garrosh_warlords_challenge",
			"storm_ui_icon_garrosh_decimate",
			"storm_ui_icon_garrosh_wrecking_ball",
			"storm_ui_icon_garrosh_slam"
		]
	],

	diablo:
	[
		[
			"storm_ui_icon_diablo_combo_1",
			"storm_ui_icon_diablo_blacksoulstone_var1",
			"storm_ui_icon_talent_spellshield"
		],
		[
			"storm_ui_icon_diablo_shadowcharge_var1",
			"storm_ui_icon_diablo_firestomp",
			"storm_ui_icon_talent_autoattack_heal"
		],
		[
			"storm_ui_icon_diablo_firestomp",
			"storm_ui_icon_talent_autoattack_damage",
			"storm_ui_icon_diablo_combo_1"
		],
		[
			"storm_ui_icon_diablo_apocalypse",
			"storm_ui_icon_diablo_lightningbreath"
		],
		[
			"storm_ui_icon_diablo_shadowcharge_var1",
			"storm_ui_icon_diablo_firestomp",
			"storm_ui_icon_diablo_combo_1"
		],
		[
			"storm_ui_icon_diablo_shadowcharge_var1",
			"storm_ui_icon_diablo_firestomp",
			"storm_ui_icon_diablo_overpower_var1"
		],
		[
			"storm_ui_icon_diablo_apocalypse",
			"storm_ui_icon_diablo_lightningbreath",
			"storm_ui_icon_diablo_lordofterror",
			"storm_ui_icon_talent_boltofthestorm"
		]
	],

	yrel:
	[
		[
			"storm_ui_icon_yrel_vindication",
			"storm_ui_icon_talent_abilitytalent_armor",
			"storm_ui_icon_talent_autoattack_heal"
		],
		[
			"storm_ui_icon_yrel_avenging_wrath",
			"storm_ui_icon_yrel_divine_purpose",
			"storm_ui_icon_yrel_hand_of_freedom"
		],
		[
			"storm_ui_icon_yrel_righteous_hammer",
			"storm_ui_icon_yrel_avenging_wrath",
			"storm_ui_icon_yrel_divine_steed"
		],
		[
			"storm_ui_icon_yrel_ardent_defender",
			"storm_ui_icon_yrel_sacred_ground"
		],
		[
			"storm_ui_icon_yrel_vindication",
			"storm_ui_icon_yrel_avenging_wrath",
			"storm_ui_icon_yrel_velens_chosen"
		],
		[
			"storm_ui_icon_yrel_righteous_hammer",
			"storm_ui_icon_yrel_divine_purpose",
			"storm_ui_icon_talent_autoattack_aoe"
		],
		[
			"storm_ui_icon_yrel_ardent_defender",
			"storm_ui_icon_yrel_sacred_ground",
			"storm_ui_icon_yrel_bubble_hearth",
			"storm_ui_icon_yrel_seraphim"
		]
	],

	hanzo:
	[
		[
			"storm_ui_icon_hanzo_stormbow",
			"storm_ui_icon_hanzo_scatterarrow",
			"storm_ui_icon_hanzo_redemption"
		],
		[
			"storm_ui_icon_hanzo_stormbow",
			"storm_ui_icon_hanzo_scatterarrow",
			"storm_ui_icon_hanzo_fromonething"
		],
		[
			"storm_ui_icon_hanzo_draconicadvantage",
			"storm_ui_icon_hanzo_scatterarrow",
			"storm_ui_icon_hanzo_shieldbreaker"
		],
		[
			"storm_ui_icon_hanzo_dragonstrike",
			"storm_ui_icon_hanzo_thedragonsarrow"
		],
		[
			"storm_ui_icon_hanzo_stormbow",
			"storm_ui_icon_hanzo_wallvault",
			"storm_ui_icon_hanzo_grabthereins"
		],
		[
			"storm_ui_icon_hanzo_fromonething",
			"storm_ui_icon_hanzo_piercingarrows",
			"storm_ui_icon_hanzo_kaijuhunter"
		],
		[
			"storm_ui_icon_hanzo_dragonstrike",
			"storm_ui_icon_hanzo_thedragonsarrow",
			"storm_ui_icon_hanzo_sonicarrow",
			"storm_ui_icon_hanzo_wallvault"
		]
	],

	medivh:
	[
		[
			"storm_ui_icon_medivh_ravenform",
			"storm_ui_icon_medivh_ravenform_b",
			"storm_ui_icon_medivh_portal"
		],
		[
			"storm_ui_icon_medivh_portal",
			"storm_ui_icon_medivh_portal_a",
			"storm_ui_icon_medivh_dustofappearance"
		],
		[
			"storm_ui_icon_medivh_arcanemissile",
			"storm_ui_icon_medivh_forceofwill",
			"storm_ui_icon_medivh_forceofwill_b"
		],
		[
			"storm_ui_icon_medivh_polybomb",
			"storm_ui_icon_medivh_leylineblast"
		],
		[
			"storm_ui_icon_medivh_forceofwill",
			"storm_ui_icon_medivh_forceofwill_a",
			"storm_ui_icon_medivh_forceofwill_b"
		],
		[
			"storm_ui_icon_medivh_arcanemissile",
			"storm_ui_icon_medivh_arcanemissile_a",
			"storm_ui_icon_medivh_portal"
		],
		[
			"storm_ui_icon_medivh_polybomb",
			"storm_ui_icon_medivh_leylineblast",
			"storm_ui_icon_medivh_arcanemissile",
			"storm_ui_icon_jaina_arcaneintellect",
			"storm_ui_icon_medivh_invisibility"
		]
	],

	gall:
	[
		[
			"storm_ui_icon_gall_shove",
			"storm_ui_icon_gall_shove_a",
			"storm_ui_icon_gall_eyeofkilrogg"
		],
		[
			"storm_ui_icon_gall_chaoscollision",
			"storm_ui_icon_gall_detonaterunes",
			"storm_ui_icon_cho_runebomb_var1"
		],
		[
			"storm_ui_icon_gall_shadowflame",
			"storm_ui_icon_gall_shadowflame_var1",
			"storm_ui_icon_gall_ogrerage"
		],
		[
			"storm_ui_icon_gall_shadowboltvolley",
			"storm_ui_icon_gall_twistingnether_a"
		],
		[
			"storm_ui_icon_gall_shadowflame",
			"storm_ui_icon_gall_psychoticbreak",
			"storm_ui_icon_gall_chaoscollision_var1"
		],
		[
			"storm_ui_icon_gall_chaoscollision",
			"storm_ui_icon_gall_detonaterunes",
			"storm_ui_icon_gall_twoheaded"
		],
		[
			"storm_ui_icon_gall_shadowboltvolley",
			"storm_ui_icon_gall_twistingnether_a",
			"storm_ui_icon_gall_ogrerage",
			"storm_ui_icon_gall_psychoticbreak"
		]
	],

	chen:
	[
		[
			"storm_ui_icon_chen_kegsmash",
			"storm_ui_icon_chen_fortifyingbrew",
			"storm_ui_icon_chen_stormstoutsecretrecipe"
		],
		[
			"storm_ui_icon_chen_flyingkick",
			"storm_ui_icon_chen_breathoffire",
			"storm_ui_icon_chen_breathoffire_a"
		],
		[
			"storm_ui_icon_chen_stagger",
			"storm_ui_icon_chen_fortifyingbrew",
			"storm_ui_icon_chen_elusivebrew"
		],
		[
			"storm_ui_icon_chen_wanderingkeg",
			"storm_ui_icon_chen_stormearthfire"
		],
		[
			"storm_ui_icon_chen_flyingkick",
			"storm_ui_icon_chen_kegsmash",
			"storm_ui_icon_chen_breathoffire",
			"storm_ui_icon_chen_fortifyingbrew"
		],
		[
			"storm_ui_icon_chen_flyingkick",
			"storm_ui_icon_chen_stagger",
			"storm_ui_icon_chen_fortifyingbrew"
		],
		[
			"storm_ui_icon_chen_wanderingkeg",
			"storm_ui_icon_chen_stormearthfire",
			"storm_ui_icon_chen_fortifyingbrew",
			"storm_ui_icon_chen_fortifyingbrew_b"
		]
	],

	lostvikings:
	[
		[
			"storm_ui_icon_lostvikings_selectolaf",
			"storm_ui_icon_lostvikings_selecterik",
			"storm_ui_icon_lostvikings_selectbaleog",
			"storm_ui_icon_talent_bribe"
		],
		[
			"storm_ui_icon_lostvikings_selectbaleog",
			"storm_ui_icon_lostvikings_selecterik",
			"storm_ui_icon_lostvikings_selecterik_var1",
			"storm_ui_icon_talent_mercenarylord"
		],
		[
			"storm_ui_icon_lostvikings_selectbaleog",
			"storm_ui_icon_lostvikings_spintowin",
			"storm_ui_icon_lostvikings_norseforce"
		],
		[
			"storm_ui_icon_lostvikings_longboatraid",
			"storm_ui_icon_lostvikings_playagain"
		],
		[
			"storm_ui_icon_lostvikings_selectolaf",
			"storm_ui_icon_lostvikings_jump",
			"storm_ui_icon_talent_autoattack_damage"
		],
		[
			"storm_ui_icon_lostvikings_selectolaf",
			"storm_ui_icon_talent_autoattack_cooldown",
			"storm_ui_icon_lostvikings_64kbmarathon",
			"storm_ui_icon_talent_autoattack_damage"
		],
		[
			"storm_ui_icon_lostvikings_longboatraid",
			"storm_ui_icon_lostvikings_playagain",
			"storm_ui_icon_lostvikings_fastrestart",
			"storm_ui_icon_talent_autoattack_damage"
		]
	],

	dehaka:
	[
		[
			"storm_ui_icon_dehaka_trample",
			"storm_ui_icon_dehaka_essencecollection",
			"storm_ui_icon_dehaka_brushstalker"
		],
		[
			"storm_ui_icon_dehaka_burrow",
			"storm_ui_icon_dehaka_essencecollection",
			"storm_ui_icon_dehaka_essencecollection_var1"
		],
		[
			"storm_ui_icon_dehaka_drag",
			"storm_ui_icon_dehaka_drag_var1",
			"storm_ui_icon_dehaka_trample"
		],
		[
			"storm_ui_icon_dehaka_isolation",
			"storm_ui_icon_dehaka_adaptation"
		],
		[
			"storm_ui_icon_dehaka_trample",
			"storm_ui_icon_dehaka_trample_a",
			"storm_ui_icon_dehaka_essencecollection"
		],
		[
			"storm_ui_icon_dehaka_drag_var1",
			"storm_ui_icon_dehaka_burrow",
			"storm_ui_icon_dehaka_brushstalker"
		],
		[
			"storm_ui_icon_dehaka_isolation",
			"storm_ui_icon_dehaka_adaptation",
			"storm_ui_icon_dehaka_essencecollection",
			"storm_ui_icon_dehaka_brushstalker"
		]
	],

	malfurion:
	[
		[
			"storm_ui_icon_malfurion_entanglingroots",
			"storm_ui_icon_malfurion_entanglingroots_b",
			"storm_ui_icon_malfurion_entanglingroots_a"
		],
		[
			"storm_ui_icon_malfurion_regrowth",
			"storm_ui_icon_malfurion_moonfire",
			"storm_ui_icon_malfurion_innerrvate"
		],
		[
			"storm_ui_icon_malfurion_wildgrowth",
			"storm_ui_icon_malfurion_entanglingroots",
			"storm_ui_icon_malfurion_regrowth"
		],
		[
			"storm_ui_icon_malfurion_tranquility",
			"storm_ui_icon_malfurion_twilightdream"
		],
		[
			"storm_ui_icon_malfurion_regrowth",
			"storm_ui_icon_malfurion_moonfire",
			"storm_ui_icon_malfurion_innerrvate"
		],
		[
			"storm_ui_icon_malfurion_regrowth",
			"storm_ui_icon_malfurion_wildgrowth",
			"storm_ui_icon_malfurion_wildgrowth_a"
		],
		[
			"storm_ui_icon_malfurion_tranquility",
			"storm_ui_icon_malfurion_twilightdream",
			"storm_ui_icon_malfurion_regrowth",
			"storm_ui_icon_malfurion_moonfire_a"
		]
	],

	dva:
	[
		[
			"storm_ui_icon_dva_mechmode",
			"storm_ui_icon_dva_mechmode_a",
			"storm_ui_icon_dva_mechmode_b"
		],
		[
			"storm_ui_icon_dva_boosters",
			"storm_ui_icon_dva_defensematrix",
			"storm_ui_icon_dva_selfdestruct"
		],
		[
			"storm_ui_icon_dva_boosters",
			"storm_ui_icon_dva_boosters_a",
			"storm_ui_icon_dva_defensematrix"
		],
		[
			"storm_ui_icon_dva_bunnyhop",
			"storm_ui_icon_dva_micromissiles"
		],
		[
			"storm_ui_icon_dva_defensematrix",
			"storm_ui_icon_dva_pilotmode",
			"storm_ui_icon_dva_bigshot"
		],
		[
			"storm_ui_icon_dva_boosters",
			"storm_ui_icon_dva_defensematrix",
			"storm_ui_icon_dva_mechmode"
		],
		[
			"storm_ui_icon_dva_bunnyhop",
			"storm_ui_icon_dva_micromissiles",
			"storm_ui_icon_dva_bigshot",
			"storm_ui_icon_dva_mechmode"
		]
	],

	malganis:
	[
		[
			"storm_ui_icon_malganis_necrotic",
			"storm_ui_icon_malganis_trait",
			"storm_ui_icon_malganis_trait_b"
		],
		[
			"storm_ui_icon_malganis_necrotic",
			"storm_ui_icon_malganis_necrotic_b",
			"storm_ui_icon_malganis_necrotic_c"
		],
		[
			"storm_ui_icon_malganis_fel_1",
			"storm_ui_icon_malganis_fel_1_b",
			"storm_ui_icon_malganis_nightrush"
		],
		[
			"storm_ui_icon_malganis_ult_swarm",
			"storm_ui_icon_malganis_ult_conversion"
		],
		[
			"storm_ui_icon_malganis_nightrush",
			"storm_ui_icon_malganis_nightrush_b",
			"storm_ui_icon_malganis_trait"
		],
		[
			"storm_ui_icon_malganis_necrotic",
			"storm_ui_icon_malganis_trait",
			"storm_ui_icon_malganis_blindbat"
		],
		[
			"storm_ui_icon_malganis_ult_swarm",
			"storm_ui_icon_malganis_ult_conversion",
			"storm_ui_icon_malganis_fel_1",
			"storm_ui_icon_malganis_nightrush"
		]
	],

	auriel:
	[
		[
			"storm_ui_icon_auriel_angelicsweep",
			"storm_ui_icon_auriel_angelicsweep_b",
			"storm_ui_icon_auriel_rayofheaven"
		],
		[
			"storm_ui_icon_auriel_angelicsweep",
			"storm_ui_icon_auriel_restrainingblow",
			"storm_ui_icon_auriel_restrainingblow_a"
		],
		[
			"storm_ui_icon_auriel_rayofheaven",
			"storm_ui_icon_auriel_bestowhope",
			"storm_ui_icon_auriel_bestowhope_a"
		],
		[
			"storm_ui_icon_auriel_resurrect",
			"storm_ui_icon_auriel_ribboncocoon"
		],
		[
			"storm_ui_icon_auriel_angelicsweep",
			"storm_ui_icon_auriel_angelicsweep_b",
			"storm_ui_icon_auriel_restrainingblow"
		],
		[
			"storm_ui_icon_auriel_rayofheaven",
			"storm_ui_icon_auriel_bestowhope",
			"storm_ui_icon_auriel_bestowhope_a"
		],
		[
			"storm_ui_icon_auriel_resurrect",
			"storm_ui_icon_auriel_ribboncocoon",
			"storm_ui_icon_auriel_angelicflight",
			"storm_ui_icon_auriel_shieldofhope"
		]
	],

	samuro:
	[
		[
			"storm_ui_icon_samuro_mirrorimage",
			"storm_ui_icon_samuro_criticalstrike",
			"storm_ui_icon_samuro_windwalk"
		],
		[
			"storm_ui_icon_samuro_mirrorimage",
			"storm_ui_icon_samuro_windwalk",
			"storm_ui_icon_samuro_flowingstrikes"
		],
		[
			"storm_ui_icon_samuro_criticalstrike",
			"storm_ui_icon_samuro_criticalstrike_a",
			"storm_ui_icon_samuro_criticalstrike_b"
		],
		[
			"storm_ui_icon_samuro_bladestorm",
			"storm_ui_icon_samuro_illusiondancer"
		],
		[
			"storm_ui_icon_samuro_mirrorimage",
			"storm_ui_icon_samuro_windwalk",
			"storm_ui_icon_samuro_windwalk_a"
		],
		[
			"storm_ui_icon_samuro_criticalstrike",
			"storm_ui_icon_samuro_windwalk",
			"storm_ui_icon_samuro_flowingstrikes"
		],
		[
			"storm_ui_icon_samuro_bladestorm",
			"storm_ui_icon_samuro_illusiondancer",
			"storm_ui_icon_samuro_windwalk",
			"storm_ui_icon_samuro_flowingstrikes"
		]
	],

	uther:
	[
		[
			"storm_ui_icon_uther_holylight",
			"storm_ui_icon_uther_holyradiance",
			"storm_ui_icon_talent_autoattack_mana"
		],
		[
			"storm_ui_icon_uther_holylight",
			"storm_ui_icon_uther_hammerofjustice",
			"storm_ui_icon_uther_holyfire"
		],
		[
			"storm_ui_icon_uther_holylight",
			"storm_ui_icon_uther_eternaldevotion",
			"storm_ui_icon_talent_cleanse"
		],
		[
			"storm_ui_icon_uther_divineshield",
			"storm_ui_icon_uther_divinestorm"
		],
		[
			"storm_ui_icon_uther_holylight",
			"storm_ui_icon_uther_hammerofjustice",
			"storm_ui_icon_talent_spellshield"
		],
		[
			"storm_ui_icon_uther_holylight",
			"storm_ui_icon_uther_holyradiance",
			"storm_ui_icon_uther_benediction"
		],
		[
			"storm_ui_icon_uther_divineshield",
			"storm_ui_icon_uther_divinestorm",
			"storm_ui_icon_uther_eternaldevotion",
			"storm_ui_icon_uther_eternaldevotion_a"
		]
	],

	thebutcher:
	[
		[
			"storm_ui_icon_butcher_hamstring",
			"storm_ui_icon_talent_block",
			"storm_ui_icon_butcher_hamstring_var1"
		],
		[
			"storm_ui_icon_butcher_hamstring",
			"storm_ui_icon_butcher_fullboar",
			"storm_ui_icon_butcher_hamstring_var1"
		],
		[
			"storm_ui_icon_butcher_tenderize",
			"storm_ui_icon_butcher_freshmeat",
			"storm_ui_icon_butcher_fullboar"
		],
		[
			"storm_ui_icon_butcher_furnaceblast",
			"storm_ui_icon_butcher_lambtotheslaughter"
		],
		[
			"storm_ui_icon_talent_autoattack_aoe",
			"storm_ui_icon_butcher_fullboar",
			"storm_ui_icon_butcher_hamstring"
		],
		[
			"storm_ui_icon_butcher_hamstring",
			"storm_ui_icon_butcher_enraged",
			"storm_ui_icon_talent_autoattack_speed"
		],
		[
			"storm_ui_icon_butcher_furnaceblast",
			"storm_ui_icon_butcher_lambtotheslaughter",
			"storm_ui_icon_talent_autoattack_slow",
			"storm_ui_icon_talent_boltofthestorm"
		]
	],

	gazlowe:
	[
		[
			"storm_ui_icon_gazlowe_explodiumcharge",
			"storm_ui_icon_gazlowe_salvager",
			"storm_ui_icon_talent_autoattack_damage"
		],
		[
			"storm_ui_icon_gazlowe_rockitturret",
			"storm_ui_icon_gazlowe_combo_w_e",
			"storm_ui_icon_talent_imposingpresence"
		],
		[
			"storm_ui_icon_gazlowe_combo_q_w",
			"storm_ui_icon_gazlowe_dethlazor_a",
			"storm_ui_icon_gazlowe_combo_w_e"
		],
		[
			"storm_ui_icon_gazlowe_robogoblin",
			"storm_ui_icon_gazlowe_gravobomb"
		],
		[
			"storm_ui_icon_gazlowe_rockitturret",
			"storm_ui_icon_gazlowe_rockitturret_var1",
			"storm_ui_icon_gazlowe_rockitturret_var2"
		],
		[
			"storm_ui_icon_gazlowe_dethlazor",
			"storm_ui_icon_gazlowe_explodiumcharge",
			"storm_ui_icon_talent_autoattack_searing"
		],
		[
			"storm_ui_icon_gazlowe_robogoblin",
			"storm_ui_icon_gazlowe_gravobomb",
			"storm_ui_icon_gazlowe_rockitturret",
			"storm_ui_icon_gazlowe_explodiumcharge"
		]
	],

	deckard:
	[
		[
			"storm_ui_icon_deckard_scroll_of_sealing",
			"storm_ui_icon_deckard_scroll_of_sealing_a",
			"storm_ui_icon_deckard_sapphire"
		],
		[
			"storm_ui_icon_deckard_healing_potion",
			"storm_ui_icon_deckard_rejuvination_potion",
			"storm_ui_icon_deckard_ruby"
		],
		[
			"storm_ui_icon_deckard_horadric_cube",
			"storm_ui_icon_deckard_kanais_cube",
			"storm_ui_icon_deckard_emerald"
		],
		[
			"storm_ui_icon_deckard_stay_awhile_and_listen",
			"storm_ui_icon_deckard_lorenado"
		],
		[
			"storm_ui_icon_deckard_super_healing_potion",
			"storm_ui_icon_deckard_unstable_healing_potion",
			"storm_ui_icon_deckard_angelic_conduit"
		],
		[
			"storm_ui_icon_deckard_scroll_of_sealing",
			"storm_ui_icon_deckard_study_time",
			"storm_ui_icon_deckard_horadric_staff"
		],
		[
			"storm_ui_icon_deckard_stay_awhile_and_listen",
			"storm_ui_icon_deckard_lorenado",
			"storm_ui_icon_deckard_healing_potion",
			"storm_ui_icon_deckard_perfect_gems"
		]
	],

	kelthuzad:
	[
		[
			"storm_ui_icon_kel_thuzad_deathanddecay",
			"storm_ui_icon_kel_thuzad_frostnova",
			"storm_ui_icon_kel_thuzad_chains"
		],
		[
			"storm_ui_icon_kel_thuzad_chains",
			"storm_ui_icon_kel_thuzad_phylactery",
			"storm_ui_icon_kel_thuzad_armorofthearchlich"
		],
		[
			"storm_ui_icon_kel_thuzad_deathanddecay",
			"storm_ui_icon_kel_thuzad_chillingtouch",
			"storm_ui_icon_kel_thuzad_glacialspike"
		],
		[
			"storm_ui_icon_kel_thuzad_frozentomb",
			"storm_ui_icon_kel_thuzad_shadowfissure"
		],
		[
			"storm_ui_icon_kel_thuzad_frostnova",
			"storm_ui_icon_kel_thuzad_chains",
			"storm_ui_icon_kel_thuzad_chains_a"
		],
		[
			"storm_ui_icon_kel_thuzad_deathanddecay",
			"storm_ui_icon_talent_abilitytalent_damage",
			"storm_ui_icon_kel_thuzad_poweroficecrown"
		],
		[
			"storm_ui_icon_kel_thuzad_frozentomb",
			"storm_ui_icon_kel_thuzad_shadowfissure",
			"storm_ui_icon_kel_thuzad_shiftingmalice",
			"storm_ui_icon_kel_thuzad_cultofthedamned"
		]
	],

	rexxar:
	[
		[
			"storm_ui_icon_rexxar_spiritswoop",
			"storm_ui_icon_rexxar_heremishaactive",
			"storm_ui_icon_rexxar_flare"
		],
		[
			"storm_ui_icon_rexxar_heremishaactive",
			"storm_ui_icon_talent_regenerationmaster",
			"storm_ui_icon_talent_block",
			"storm_ui_icon_rexxar_stayinalive"
		],
		[
			"storm_ui_icon_rexxar_spiritswoop",
			"storm_ui_icon_rexxar_spiritswoop_var1",
			"storm_ui_icon_rexxar_mishacharge"
		],
		[
			"storm_ui_icon_rexxar_bestialwrath",
			"storm_ui_icon_rexxar_unleashtheboars"
		],
		[
			"storm_ui_icon_rexxar_spiritswoop",
			"storm_ui_icon_rexxar_mishacharge",
			"storm_ui_icon_talent_burningrage"
		],
		[
			"storm_ui_icon_rexxar_heremishaactive",
			"storm_ui_icon_talent_imposingpresence",
			"storm_ui_icon_rexxar_feigndeath"
		],
		[
			"storm_ui_icon_rexxar_bestialwrath",
			"storm_ui_icon_rexxar_unleashtheboars",
			"storm_ui_icon_talent_autoattack_slow",
			"storm_ui_icon_talent_hardenedshield"
		]
	],
}