const heroRoles = {
  "abathur": "melee",
  "alarak": "melee",
  "alexstrasza": "healer",
  "ana": "healer",
  "anduin": "healer",
  "anubarak": "tank",
  "artanis": "bruiser",
  "arthas": "tank",
  "auriel": "healer",
  "azmodan": "ranged",
  "blaze": "bruiser",
  "brightwing": "healer",
  "cassia": "ranged",
  "chen": "bruiser",
  "cho": "tank",
  "chromie": "ranged",
  "dva": "bruiser",
  "deathwing": "bruiser",
  "deckard": "healer",
  "dehaka": "bruiser",
  "diablo": "tank",
  "etc": "tank",
  "falstad": "ranged",
  "fenix": "ranged",
  "gall": "ranged",
  "garrosh": "tank",
  "gazlowe": "bruiser",
  "genji": "melee",
  "greymane": "ranged",
  "guldan": "ranged",
  "hanzo": "ranged",
  "hogger": "bruiser",
  "illidan": "bruiser",
  "imperius": "bruiser",
  "jaina": "ranged",
  "johanna": "tank",
  "junkrat": "ranged",
  "kaelthas": "ranged",
  "kelthuzad": "ranged",
  "kerrigan": "melee",
  "kharazim": "healer",
  "leoric": "bruiser",
  "lili": "healer",
  "liming": "ranged",
  "ltmorales": "healer",
  "lucio": "healer",
  "lunara": "ranged",
  "maiev": "melee",
  "malfurion": "healer",
  "malganis": "tank",
  "malthael": "bruiser",
  "medivh": "melee",
  "mei": "tank",
  "mephisto": "ranged",
  "muradin": "tank",
  "murky": "bruiser",
  "nazeebo": "ranged",
  "nova": "ranged",
  "orphea": "ranged",
  "probius": "ranged",
  "qhira": "melee",
  "ragnaros": "bruiser",
  "raynor": "ranged",
  "rehgar": "healer",
  "rexxar": "bruiser",
  "samuro": "bruiser",
  "sgthammer": "ranged",
  "sonya": "bruiser",
  "stitches": "tank",
  "stukov": "healer",
  "sylvanas": "ranged",
  "tassadar": "ranged",
  "thebutcher": "melee",
  "lostvikings": "bruiser",
  "thrall": "melee",
  "tracer": "ranged",
  "tychus": "ranged",
  "tyrael": "tank",
  "tyrande": "healer",
  "uther": "healer",
  "valeera": "melee",
  "valla": "ranged",
  "varian": "bruiser",
  "whitemane": "healer",
  "xul": "bruiser",
  "yrel": "bruiser",
  "zagara": "ranged",
  "zarya": "melee",
  "zeratul": "melee",
  "zuljin": "ranged"
};

function filterHeroesByRole(role) {
  return Object.entries(heroRoles)
    .filter(([_, heroRole]) => heroRole === role)
    .map(([hero, _]) => hero);
}

const melee = filterHeroesByRole("melee");
const healer = filterHeroesByRole("healer");
const tank = filterHeroesByRole("tank");
const bruiser = filterHeroesByRole("bruiser");
const ranged = filterHeroesByRole("ranged");
